/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_flip CASADI_PREFIX(flip)
#define casadi_interpn CASADI_PREFIX(interpn)
#define casadi_interpn_interpolate CASADI_PREFIX(interpn_interpolate)
#define casadi_interpn_weights CASADI_PREFIX(interpn_weights)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_interpn_weights(casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* x, casadi_real* alpha, casadi_int* index, const casadi_int* lookup_mode) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    casadi_int ng, j;
    casadi_real xi;
    const casadi_real* g;
    xi = x ? x[i] : 0;
    g = grid + offset[i];
    ng = offset[i+1]-offset[i];
    j = index[i] = casadi_low(xi, g, ng, lookup_mode[i]);
    alpha[i] = (xi-g[j])/(g[j+1]-g[j]);
  }
}

void casadi_interpn_interpolate(casadi_real* res, casadi_int ndim, const casadi_int* offset, const casadi_real* values, const casadi_real* alpha, const casadi_int* index, const casadi_int* corner, casadi_real* coeff, casadi_int m) {
  casadi_real c;
  casadi_int ld, i;
  c=1;
  ld=1;
  for (i=0; i<ndim; ++i) {
    if (coeff) *coeff++ = c;
    if (corner[i]) {
      c *= alpha[i];
    } else {
      c *= 1-alpha[i];
    }
    values += (index[i]+corner[i])*ld*m;
    ld *= offset[i+1]-offset[i];
  }
  if (coeff) {
    for (i=0;i<m;++i) res[i] += values[i];
  } else {
    for (i=0;i<m;++i) res[i] += c*values[i];
  }
}

casadi_int casadi_flip(casadi_int* corner, casadi_int ndim) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    if (corner[i]) {
      corner[i]=0;
    } else {
      corner[i]=1;
      return 1;
    }
  }
  return 0;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_interpn(casadi_real* res, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real* alpha;
  casadi_int *index, *corner;
  alpha = w; w += ndim;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(res, m);
  do {
    casadi_real* coeff = 0;
    casadi_interpn_interpolate(res, ndim, offset, values,
      alpha, index, corner, coeff, m);
  } while (casadi_flip(corner, ndim));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[2] = {0, 20};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {3};
static const casadi_int casadi_s4[2] = {0, 64};
static const casadi_int casadi_s5[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[70] = {66, 1, 0, 66, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65};
static const casadi_int casadi_s8[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[20] = {0., 5.2631578947368418e-02, 1.0526315789473684e-01, 1.5789473684210525e-01, 2.1052631578947367e-01, 2.6315789473684209e-01, 3.1578947368421051e-01, 3.6842105263157893e-01, 4.2105263157894735e-01, 4.7368421052631576e-01, 5.2631578947368418e-01, 5.7894736842105265e-01, 6.3157894736842102e-01, 6.8421052631578938e-01, 7.3684210526315785e-01, 7.8947368421052633e-01, 8.4210526315789469e-01, 8.9473684210526305e-01, 9.4736842105263153e-01, 1.};
static const casadi_real casadi_c1[60] = {0., 8.5964912280701664e-03, 1.7543859649122806e-02, 3.5087719298245612e-02, 5.2631578947368418e-02, 7.0175438596491224e-02, 8.7719298245614030e-02, 1.0526315789473684e-01, 1.2280701754385964e-01, 1.4035087719298245e-01, 1.5789473684210528e-01, 1.7543859649122806e-01, 1.9298245614035089e-01, 2.1052631578947367e-01, 2.2807017543859645e-01, 2.4561403508771928e-01, 2.6315789473684209e-01, 2.8070175438596490e-01, 2.9824561403508770e-01, 3.1578947368421051e-01, 3.3333333333333331e-01, 3.5087719298245612e-01, 3.6842105263157893e-01, 3.8596491228070179e-01, 4.0350877192982454e-01, 4.2105263157894735e-01, 4.3859649122807015e-01, 4.5614035087719290e-01, 4.7368421052631576e-01, 4.9122807017543857e-01, 5.0877192982456132e-01, 5.2631578947368418e-01, 5.4385964912280693e-01, 5.6140350877192979e-01, 5.7894736842105265e-01, 5.9649122807017552e-01, 6.1403508771929827e-01, 6.3157894736842091e-01, 6.4912280701754377e-01, 6.6666666666666663e-01, 6.8421052631578938e-01, 7.0175438596491224e-01, 7.1929824561403510e-01, 7.3684210526315785e-01, 7.5438596491228072e-01, 7.7192982456140358e-01, 7.8947368421052622e-01, 8.0701754385964908e-01, 8.2456140350877194e-01, 8.4210526315789469e-01, 8.5964912280701755e-01, 8.7719298245614030e-01, 8.9473684210526294e-01, 9.1228070175438580e-01, 9.2982456140350866e-01, 9.4736842105263153e-01, 9.6491228070175428e-01, 9.8245614035087714e-01, 9.9140350877192984e-01, 1.};
static const casadi_real casadi_c2[64] = {0., 0., 0., 0., 2.5789473684210498e-02, 2.6842105263157921e-02, 5.2631578947368418e-02, 7.8421052631578919e-02, 7.9473684210526335e-02, 1.0526315789473684e-01, 1.3105263157894734e-01, 1.3210526315789475e-01, 1.5789473684210525e-01, 1.8368421052631576e-01, 1.8473684210526317e-01, 2.1052631578947367e-01, 2.3631578947368417e-01, 2.3736842105263159e-01, 2.6315789473684209e-01, 2.8894736842105256e-01, 2.9000000000000004e-01, 3.1578947368421051e-01, 3.4157894736842098e-01, 3.4263157894736845e-01, 3.6842105263157893e-01, 3.9421052631578940e-01, 3.9526315789473687e-01, 4.2105263157894735e-01, 4.4684210526315782e-01, 4.4789473684210529e-01, 4.7368421052631576e-01, 4.9947368421052624e-01, 5.0052631578947371e-01, 5.2631578947368418e-01, 5.5210526315789465e-01, 5.5315789473684218e-01, 5.7894736842105265e-01, 6.0473684210526313e-01, 6.0578947368421054e-01, 6.3157894736842102e-01, 6.5736842105263149e-01, 6.5842105263157891e-01, 6.8421052631578938e-01, 7.0999999999999985e-01, 7.1105263157894738e-01, 7.3684210526315785e-01, 7.6263157894736833e-01, 7.6368421052631585e-01, 7.8947368421052633e-01, 8.1526315789473680e-01, 8.1631578947368422e-01, 8.4210526315789469e-01, 8.6789473684210516e-01, 8.6894736842105258e-01, 8.9473684210526305e-01, 9.2052631578947353e-01, 9.2157894736842105e-01, 9.4736842105263153e-01, 9.7315789473684200e-01, 9.7421052631578953e-01, 1., 1., 1., 1.};

/* linear:(x,c[20])->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* x:(x,c[20])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, *w62=w+130, w63;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.00859649, 0.0175439, 0.0350877, 0.0526316, 0.0701754, 0.0877193, 0.105263, 0.122807, 0.140351, 0.157895, 0.175439, 0.192982, 0.210526, 0.22807, 0.245614, 0.263158, 0.280702, 0.298246, 0.315789, 0.333333, 0.350877, 0.368421, 0.385965, 0.403509, 0.421053, 0.438596, 0.45614, 0.473684, 0.491228, 0.508772, 0.526316, 0.54386, 0.561404, 0.578947, 0.596491, 0.614035, 0.631579, 0.649123, 0.666667, 0.684211, 0.701754, 0.719298, 0.736842, 0.754386, 0.77193, 0.789474, 0.807018, 0.824561, 0.842105, 0.859649, 0.877193, 0.894737, 0.912281, 0.929825, 0.947368, 0.964912, 0.982456, 0.991404, 1]] */
  casadi_copy(casadi_c1, 60, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56, @57, @58, @59, @60, @61} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  w20 = w1[18];
  w21 = w1[19];
  w22 = w1[20];
  w23 = w1[21];
  w24 = w1[22];
  w25 = w1[23];
  w26 = w1[24];
  w27 = w1[25];
  w28 = w1[26];
  w29 = w1[27];
  w30 = w1[28];
  w31 = w1[29];
  w32 = w1[30];
  w33 = w1[31];
  w34 = w1[32];
  w35 = w1[33];
  w36 = w1[34];
  w37 = w1[35];
  w38 = w1[36];
  w39 = w1[37];
  w40 = w1[38];
  w41 = w1[39];
  w42 = w1[40];
  w43 = w1[41];
  w44 = w1[42];
  w45 = w1[43];
  w46 = w1[44];
  w47 = w1[45];
  w48 = w1[46];
  w49 = w1[47];
  w50 = w1[48];
  w51 = w1[49];
  w52 = w1[50];
  w53 = w1[51];
  w54 = w1[52];
  w55 = w1[53];
  w56 = w1[54];
  w57 = w1[55];
  w58 = w1[56];
  w59 = w1[57];
  w60 = w1[58];
  w61 = w1[59];
  /* #3: @62 = input[1][0] */
  casadi_copy(arg[1], 20, w62);
  /* #4: @63 = linear(@2, @62) */
  arg1[0]=(&w2);
  arg1[1]=w62;
  res1[0]=(&w63);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @62) */
  arg1[0]=(&w3);
  arg1[1]=w62;
  res1[0]=(&w2);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @62) */
  arg1[0]=(&w4);
  arg1[1]=w62;
  res1[0]=(&w3);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @62) */
  arg1[0]=(&w5);
  arg1[1]=w62;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @62) */
  arg1[0]=(&w6);
  arg1[1]=w62;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @62) */
  arg1[0]=(&w7);
  arg1[1]=w62;
  res1[0]=(&w6);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @62) */
  arg1[0]=(&w8);
  arg1[1]=w62;
  res1[0]=(&w7);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @62) */
  arg1[0]=(&w9);
  arg1[1]=w62;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @62) */
  arg1[0]=(&w10);
  arg1[1]=w62;
  res1[0]=(&w9);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @62) */
  arg1[0]=(&w11);
  arg1[1]=w62;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @62) */
  arg1[0]=(&w12);
  arg1[1]=w62;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @62) */
  arg1[0]=(&w13);
  arg1[1]=w62;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @62) */
  arg1[0]=(&w14);
  arg1[1]=w62;
  res1[0]=(&w13);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @62) */
  arg1[0]=(&w15);
  arg1[1]=w62;
  res1[0]=(&w14);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @62) */
  arg1[0]=(&w16);
  arg1[1]=w62;
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @62) */
  arg1[0]=(&w17);
  arg1[1]=w62;
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @62) */
  arg1[0]=(&w18);
  arg1[1]=w62;
  res1[0]=(&w17);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @62) */
  arg1[0]=(&w19);
  arg1[1]=w62;
  res1[0]=(&w18);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @62) */
  arg1[0]=(&w20);
  arg1[1]=w62;
  res1[0]=(&w19);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @62) */
  arg1[0]=(&w21);
  arg1[1]=w62;
  res1[0]=(&w20);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #24: @21 = linear(@22, @62) */
  arg1[0]=(&w22);
  arg1[1]=w62;
  res1[0]=(&w21);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: @22 = linear(@23, @62) */
  arg1[0]=(&w23);
  arg1[1]=w62;
  res1[0]=(&w22);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #26: @23 = linear(@24, @62) */
  arg1[0]=(&w24);
  arg1[1]=w62;
  res1[0]=(&w23);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #27: @24 = linear(@25, @62) */
  arg1[0]=(&w25);
  arg1[1]=w62;
  res1[0]=(&w24);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: @25 = linear(@26, @62) */
  arg1[0]=(&w26);
  arg1[1]=w62;
  res1[0]=(&w25);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #29: @26 = linear(@27, @62) */
  arg1[0]=(&w27);
  arg1[1]=w62;
  res1[0]=(&w26);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #30: @27 = linear(@28, @62) */
  arg1[0]=(&w28);
  arg1[1]=w62;
  res1[0]=(&w27);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #31: @28 = linear(@29, @62) */
  arg1[0]=(&w29);
  arg1[1]=w62;
  res1[0]=(&w28);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #32: @29 = linear(@30, @62) */
  arg1[0]=(&w30);
  arg1[1]=w62;
  res1[0]=(&w29);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #33: @30 = linear(@31, @62) */
  arg1[0]=(&w31);
  arg1[1]=w62;
  res1[0]=(&w30);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #34: @31 = linear(@32, @62) */
  arg1[0]=(&w32);
  arg1[1]=w62;
  res1[0]=(&w31);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #35: @32 = linear(@33, @62) */
  arg1[0]=(&w33);
  arg1[1]=w62;
  res1[0]=(&w32);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #36: @33 = linear(@34, @62) */
  arg1[0]=(&w34);
  arg1[1]=w62;
  res1[0]=(&w33);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: @34 = linear(@35, @62) */
  arg1[0]=(&w35);
  arg1[1]=w62;
  res1[0]=(&w34);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #38: @35 = linear(@36, @62) */
  arg1[0]=(&w36);
  arg1[1]=w62;
  res1[0]=(&w35);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #39: @36 = linear(@37, @62) */
  arg1[0]=(&w37);
  arg1[1]=w62;
  res1[0]=(&w36);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: @37 = linear(@38, @62) */
  arg1[0]=(&w38);
  arg1[1]=w62;
  res1[0]=(&w37);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #41: @38 = linear(@39, @62) */
  arg1[0]=(&w39);
  arg1[1]=w62;
  res1[0]=(&w38);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #42: @39 = linear(@40, @62) */
  arg1[0]=(&w40);
  arg1[1]=w62;
  res1[0]=(&w39);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #43: @40 = linear(@41, @62) */
  arg1[0]=(&w41);
  arg1[1]=w62;
  res1[0]=(&w40);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #44: @41 = linear(@42, @62) */
  arg1[0]=(&w42);
  arg1[1]=w62;
  res1[0]=(&w41);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #45: @42 = linear(@43, @62) */
  arg1[0]=(&w43);
  arg1[1]=w62;
  res1[0]=(&w42);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: @43 = linear(@44, @62) */
  arg1[0]=(&w44);
  arg1[1]=w62;
  res1[0]=(&w43);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #47: @44 = linear(@45, @62) */
  arg1[0]=(&w45);
  arg1[1]=w62;
  res1[0]=(&w44);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #48: @45 = linear(@46, @62) */
  arg1[0]=(&w46);
  arg1[1]=w62;
  res1[0]=(&w45);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #49: @46 = linear(@47, @62) */
  arg1[0]=(&w47);
  arg1[1]=w62;
  res1[0]=(&w46);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #50: @47 = linear(@48, @62) */
  arg1[0]=(&w48);
  arg1[1]=w62;
  res1[0]=(&w47);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #51: @48 = linear(@49, @62) */
  arg1[0]=(&w49);
  arg1[1]=w62;
  res1[0]=(&w48);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #52: @49 = linear(@50, @62) */
  arg1[0]=(&w50);
  arg1[1]=w62;
  res1[0]=(&w49);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #53: @50 = linear(@51, @62) */
  arg1[0]=(&w51);
  arg1[1]=w62;
  res1[0]=(&w50);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #54: @51 = linear(@52, @62) */
  arg1[0]=(&w52);
  arg1[1]=w62;
  res1[0]=(&w51);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #55: @52 = linear(@53, @62) */
  arg1[0]=(&w53);
  arg1[1]=w62;
  res1[0]=(&w52);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #56: @53 = linear(@54, @62) */
  arg1[0]=(&w54);
  arg1[1]=w62;
  res1[0]=(&w53);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #57: @54 = linear(@55, @62) */
  arg1[0]=(&w55);
  arg1[1]=w62;
  res1[0]=(&w54);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #58: @55 = linear(@56, @62) */
  arg1[0]=(&w56);
  arg1[1]=w62;
  res1[0]=(&w55);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #59: @56 = linear(@57, @62) */
  arg1[0]=(&w57);
  arg1[1]=w62;
  res1[0]=(&w56);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #60: @57 = linear(@58, @62) */
  arg1[0]=(&w58);
  arg1[1]=w62;
  res1[0]=(&w57);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #61: @58 = linear(@59, @62) */
  arg1[0]=(&w59);
  arg1[1]=w62;
  res1[0]=(&w58);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #62: @59 = linear(@60, @62) */
  arg1[0]=(&w60);
  arg1[1]=w62;
  res1[0]=(&w59);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #63: @60 = linear(@61, @62) */
  arg1[0]=(&w61);
  arg1[1]=w62;
  res1[0]=(&w60);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #64: @1 = horzcat(@63, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56, @57, @58, @59, @60) */
  rr=w1;
  *rr++ = w63;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w56;
  *rr++ = w57;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w60;
  /* #65: @63 = BSplineParametric(@0) */
  casadi_clear((&w63), 1);
  CASADI_PREFIX(nd_boor_eval)((&w63),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #66: output[0][0] = @63 */
  if (res[0]) res[0][0] = w63;
  return 0;
}

/* linear:(x,c[20])->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* y:(x,c[20])->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, *w62=w+130, w63;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.00859649, 0.0175439, 0.0350877, 0.0526316, 0.0701754, 0.0877193, 0.105263, 0.122807, 0.140351, 0.157895, 0.175439, 0.192982, 0.210526, 0.22807, 0.245614, 0.263158, 0.280702, 0.298246, 0.315789, 0.333333, 0.350877, 0.368421, 0.385965, 0.403509, 0.421053, 0.438596, 0.45614, 0.473684, 0.491228, 0.508772, 0.526316, 0.54386, 0.561404, 0.578947, 0.596491, 0.614035, 0.631579, 0.649123, 0.666667, 0.684211, 0.701754, 0.719298, 0.736842, 0.754386, 0.77193, 0.789474, 0.807018, 0.824561, 0.842105, 0.859649, 0.877193, 0.894737, 0.912281, 0.929825, 0.947368, 0.964912, 0.982456, 0.991404, 1]] */
  casadi_copy(casadi_c1, 60, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56, @57, @58, @59, @60, @61} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  w20 = w1[18];
  w21 = w1[19];
  w22 = w1[20];
  w23 = w1[21];
  w24 = w1[22];
  w25 = w1[23];
  w26 = w1[24];
  w27 = w1[25];
  w28 = w1[26];
  w29 = w1[27];
  w30 = w1[28];
  w31 = w1[29];
  w32 = w1[30];
  w33 = w1[31];
  w34 = w1[32];
  w35 = w1[33];
  w36 = w1[34];
  w37 = w1[35];
  w38 = w1[36];
  w39 = w1[37];
  w40 = w1[38];
  w41 = w1[39];
  w42 = w1[40];
  w43 = w1[41];
  w44 = w1[42];
  w45 = w1[43];
  w46 = w1[44];
  w47 = w1[45];
  w48 = w1[46];
  w49 = w1[47];
  w50 = w1[48];
  w51 = w1[49];
  w52 = w1[50];
  w53 = w1[51];
  w54 = w1[52];
  w55 = w1[53];
  w56 = w1[54];
  w57 = w1[55];
  w58 = w1[56];
  w59 = w1[57];
  w60 = w1[58];
  w61 = w1[59];
  /* #3: @62 = input[1][0] */
  casadi_copy(arg[1], 20, w62);
  /* #4: @63 = linear(@2, @62) */
  arg1[0]=(&w2);
  arg1[1]=w62;
  res1[0]=(&w63);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @62) */
  arg1[0]=(&w3);
  arg1[1]=w62;
  res1[0]=(&w2);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @62) */
  arg1[0]=(&w4);
  arg1[1]=w62;
  res1[0]=(&w3);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @62) */
  arg1[0]=(&w5);
  arg1[1]=w62;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @62) */
  arg1[0]=(&w6);
  arg1[1]=w62;
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @62) */
  arg1[0]=(&w7);
  arg1[1]=w62;
  res1[0]=(&w6);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @62) */
  arg1[0]=(&w8);
  arg1[1]=w62;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @62) */
  arg1[0]=(&w9);
  arg1[1]=w62;
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @62) */
  arg1[0]=(&w10);
  arg1[1]=w62;
  res1[0]=(&w9);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @62) */
  arg1[0]=(&w11);
  arg1[1]=w62;
  res1[0]=(&w10);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @62) */
  arg1[0]=(&w12);
  arg1[1]=w62;
  res1[0]=(&w11);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @62) */
  arg1[0]=(&w13);
  arg1[1]=w62;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @62) */
  arg1[0]=(&w14);
  arg1[1]=w62;
  res1[0]=(&w13);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @62) */
  arg1[0]=(&w15);
  arg1[1]=w62;
  res1[0]=(&w14);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @62) */
  arg1[0]=(&w16);
  arg1[1]=w62;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @62) */
  arg1[0]=(&w17);
  arg1[1]=w62;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @62) */
  arg1[0]=(&w18);
  arg1[1]=w62;
  res1[0]=(&w17);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @62) */
  arg1[0]=(&w19);
  arg1[1]=w62;
  res1[0]=(&w18);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @62) */
  arg1[0]=(&w20);
  arg1[1]=w62;
  res1[0]=(&w19);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @62) */
  arg1[0]=(&w21);
  arg1[1]=w62;
  res1[0]=(&w20);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #24: @21 = linear(@22, @62) */
  arg1[0]=(&w22);
  arg1[1]=w62;
  res1[0]=(&w21);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #25: @22 = linear(@23, @62) */
  arg1[0]=(&w23);
  arg1[1]=w62;
  res1[0]=(&w22);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #26: @23 = linear(@24, @62) */
  arg1[0]=(&w24);
  arg1[1]=w62;
  res1[0]=(&w23);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #27: @24 = linear(@25, @62) */
  arg1[0]=(&w25);
  arg1[1]=w62;
  res1[0]=(&w24);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #28: @25 = linear(@26, @62) */
  arg1[0]=(&w26);
  arg1[1]=w62;
  res1[0]=(&w25);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #29: @26 = linear(@27, @62) */
  arg1[0]=(&w27);
  arg1[1]=w62;
  res1[0]=(&w26);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #30: @27 = linear(@28, @62) */
  arg1[0]=(&w28);
  arg1[1]=w62;
  res1[0]=(&w27);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #31: @28 = linear(@29, @62) */
  arg1[0]=(&w29);
  arg1[1]=w62;
  res1[0]=(&w28);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #32: @29 = linear(@30, @62) */
  arg1[0]=(&w30);
  arg1[1]=w62;
  res1[0]=(&w29);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #33: @30 = linear(@31, @62) */
  arg1[0]=(&w31);
  arg1[1]=w62;
  res1[0]=(&w30);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #34: @31 = linear(@32, @62) */
  arg1[0]=(&w32);
  arg1[1]=w62;
  res1[0]=(&w31);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #35: @32 = linear(@33, @62) */
  arg1[0]=(&w33);
  arg1[1]=w62;
  res1[0]=(&w32);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #36: @33 = linear(@34, @62) */
  arg1[0]=(&w34);
  arg1[1]=w62;
  res1[0]=(&w33);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #37: @34 = linear(@35, @62) */
  arg1[0]=(&w35);
  arg1[1]=w62;
  res1[0]=(&w34);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #38: @35 = linear(@36, @62) */
  arg1[0]=(&w36);
  arg1[1]=w62;
  res1[0]=(&w35);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #39: @36 = linear(@37, @62) */
  arg1[0]=(&w37);
  arg1[1]=w62;
  res1[0]=(&w36);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #40: @37 = linear(@38, @62) */
  arg1[0]=(&w38);
  arg1[1]=w62;
  res1[0]=(&w37);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #41: @38 = linear(@39, @62) */
  arg1[0]=(&w39);
  arg1[1]=w62;
  res1[0]=(&w38);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #42: @39 = linear(@40, @62) */
  arg1[0]=(&w40);
  arg1[1]=w62;
  res1[0]=(&w39);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #43: @40 = linear(@41, @62) */
  arg1[0]=(&w41);
  arg1[1]=w62;
  res1[0]=(&w40);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #44: @41 = linear(@42, @62) */
  arg1[0]=(&w42);
  arg1[1]=w62;
  res1[0]=(&w41);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #45: @42 = linear(@43, @62) */
  arg1[0]=(&w43);
  arg1[1]=w62;
  res1[0]=(&w42);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #46: @43 = linear(@44, @62) */
  arg1[0]=(&w44);
  arg1[1]=w62;
  res1[0]=(&w43);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #47: @44 = linear(@45, @62) */
  arg1[0]=(&w45);
  arg1[1]=w62;
  res1[0]=(&w44);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #48: @45 = linear(@46, @62) */
  arg1[0]=(&w46);
  arg1[1]=w62;
  res1[0]=(&w45);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #49: @46 = linear(@47, @62) */
  arg1[0]=(&w47);
  arg1[1]=w62;
  res1[0]=(&w46);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #50: @47 = linear(@48, @62) */
  arg1[0]=(&w48);
  arg1[1]=w62;
  res1[0]=(&w47);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #51: @48 = linear(@49, @62) */
  arg1[0]=(&w49);
  arg1[1]=w62;
  res1[0]=(&w48);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #52: @49 = linear(@50, @62) */
  arg1[0]=(&w50);
  arg1[1]=w62;
  res1[0]=(&w49);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #53: @50 = linear(@51, @62) */
  arg1[0]=(&w51);
  arg1[1]=w62;
  res1[0]=(&w50);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #54: @51 = linear(@52, @62) */
  arg1[0]=(&w52);
  arg1[1]=w62;
  res1[0]=(&w51);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #55: @52 = linear(@53, @62) */
  arg1[0]=(&w53);
  arg1[1]=w62;
  res1[0]=(&w52);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #56: @53 = linear(@54, @62) */
  arg1[0]=(&w54);
  arg1[1]=w62;
  res1[0]=(&w53);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #57: @54 = linear(@55, @62) */
  arg1[0]=(&w55);
  arg1[1]=w62;
  res1[0]=(&w54);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #58: @55 = linear(@56, @62) */
  arg1[0]=(&w56);
  arg1[1]=w62;
  res1[0]=(&w55);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #59: @56 = linear(@57, @62) */
  arg1[0]=(&w57);
  arg1[1]=w62;
  res1[0]=(&w56);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #60: @57 = linear(@58, @62) */
  arg1[0]=(&w58);
  arg1[1]=w62;
  res1[0]=(&w57);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #61: @58 = linear(@59, @62) */
  arg1[0]=(&w59);
  arg1[1]=w62;
  res1[0]=(&w58);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #62: @59 = linear(@60, @62) */
  arg1[0]=(&w60);
  arg1[1]=w62;
  res1[0]=(&w59);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #63: @60 = linear(@61, @62) */
  arg1[0]=(&w61);
  arg1[1]=w62;
  res1[0]=(&w60);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #64: @1 = horzcat(@63, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56, @57, @58, @59, @60) */
  rr=w1;
  *rr++ = w63;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w56;
  *rr++ = w57;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w60;
  /* #65: @63 = BSplineParametric(@0) */
  casadi_clear((&w63), 1);
  CASADI_PREFIX(nd_boor_eval)((&w63),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #66: output[0][0] = @63 */
  if (res[0]) res[0][0] = w63;
  return 0;
}

/* linear:(x,c[20])->(f) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* r:(x,c[20])->(f) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, *w62=w+130, w63;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.00859649, 0.0175439, 0.0350877, 0.0526316, 0.0701754, 0.0877193, 0.105263, 0.122807, 0.140351, 0.157895, 0.175439, 0.192982, 0.210526, 0.22807, 0.245614, 0.263158, 0.280702, 0.298246, 0.315789, 0.333333, 0.350877, 0.368421, 0.385965, 0.403509, 0.421053, 0.438596, 0.45614, 0.473684, 0.491228, 0.508772, 0.526316, 0.54386, 0.561404, 0.578947, 0.596491, 0.614035, 0.631579, 0.649123, 0.666667, 0.684211, 0.701754, 0.719298, 0.736842, 0.754386, 0.77193, 0.789474, 0.807018, 0.824561, 0.842105, 0.859649, 0.877193, 0.894737, 0.912281, 0.929825, 0.947368, 0.964912, 0.982456, 0.991404, 1]] */
  casadi_copy(casadi_c1, 60, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56, @57, @58, @59, @60, @61} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  w20 = w1[18];
  w21 = w1[19];
  w22 = w1[20];
  w23 = w1[21];
  w24 = w1[22];
  w25 = w1[23];
  w26 = w1[24];
  w27 = w1[25];
  w28 = w1[26];
  w29 = w1[27];
  w30 = w1[28];
  w31 = w1[29];
  w32 = w1[30];
  w33 = w1[31];
  w34 = w1[32];
  w35 = w1[33];
  w36 = w1[34];
  w37 = w1[35];
  w38 = w1[36];
  w39 = w1[37];
  w40 = w1[38];
  w41 = w1[39];
  w42 = w1[40];
  w43 = w1[41];
  w44 = w1[42];
  w45 = w1[43];
  w46 = w1[44];
  w47 = w1[45];
  w48 = w1[46];
  w49 = w1[47];
  w50 = w1[48];
  w51 = w1[49];
  w52 = w1[50];
  w53 = w1[51];
  w54 = w1[52];
  w55 = w1[53];
  w56 = w1[54];
  w57 = w1[55];
  w58 = w1[56];
  w59 = w1[57];
  w60 = w1[58];
  w61 = w1[59];
  /* #3: @62 = input[1][0] */
  casadi_copy(arg[1], 20, w62);
  /* #4: @63 = linear(@2, @62) */
  arg1[0]=(&w2);
  arg1[1]=w62;
  res1[0]=(&w63);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @62) */
  arg1[0]=(&w3);
  arg1[1]=w62;
  res1[0]=(&w2);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @62) */
  arg1[0]=(&w4);
  arg1[1]=w62;
  res1[0]=(&w3);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @62) */
  arg1[0]=(&w5);
  arg1[1]=w62;
  res1[0]=(&w4);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @62) */
  arg1[0]=(&w6);
  arg1[1]=w62;
  res1[0]=(&w5);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @62) */
  arg1[0]=(&w7);
  arg1[1]=w62;
  res1[0]=(&w6);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @62) */
  arg1[0]=(&w8);
  arg1[1]=w62;
  res1[0]=(&w7);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @62) */
  arg1[0]=(&w9);
  arg1[1]=w62;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @62) */
  arg1[0]=(&w10);
  arg1[1]=w62;
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @62) */
  arg1[0]=(&w11);
  arg1[1]=w62;
  res1[0]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @62) */
  arg1[0]=(&w12);
  arg1[1]=w62;
  res1[0]=(&w11);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @62) */
  arg1[0]=(&w13);
  arg1[1]=w62;
  res1[0]=(&w12);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @62) */
  arg1[0]=(&w14);
  arg1[1]=w62;
  res1[0]=(&w13);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @62) */
  arg1[0]=(&w15);
  arg1[1]=w62;
  res1[0]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @62) */
  arg1[0]=(&w16);
  arg1[1]=w62;
  res1[0]=(&w15);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @62) */
  arg1[0]=(&w17);
  arg1[1]=w62;
  res1[0]=(&w16);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @62) */
  arg1[0]=(&w18);
  arg1[1]=w62;
  res1[0]=(&w17);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @62) */
  arg1[0]=(&w19);
  arg1[1]=w62;
  res1[0]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @62) */
  arg1[0]=(&w20);
  arg1[1]=w62;
  res1[0]=(&w19);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @62) */
  arg1[0]=(&w21);
  arg1[1]=w62;
  res1[0]=(&w20);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #24: @21 = linear(@22, @62) */
  arg1[0]=(&w22);
  arg1[1]=w62;
  res1[0]=(&w21);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #25: @22 = linear(@23, @62) */
  arg1[0]=(&w23);
  arg1[1]=w62;
  res1[0]=(&w22);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #26: @23 = linear(@24, @62) */
  arg1[0]=(&w24);
  arg1[1]=w62;
  res1[0]=(&w23);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #27: @24 = linear(@25, @62) */
  arg1[0]=(&w25);
  arg1[1]=w62;
  res1[0]=(&w24);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #28: @25 = linear(@26, @62) */
  arg1[0]=(&w26);
  arg1[1]=w62;
  res1[0]=(&w25);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #29: @26 = linear(@27, @62) */
  arg1[0]=(&w27);
  arg1[1]=w62;
  res1[0]=(&w26);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #30: @27 = linear(@28, @62) */
  arg1[0]=(&w28);
  arg1[1]=w62;
  res1[0]=(&w27);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #31: @28 = linear(@29, @62) */
  arg1[0]=(&w29);
  arg1[1]=w62;
  res1[0]=(&w28);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #32: @29 = linear(@30, @62) */
  arg1[0]=(&w30);
  arg1[1]=w62;
  res1[0]=(&w29);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #33: @30 = linear(@31, @62) */
  arg1[0]=(&w31);
  arg1[1]=w62;
  res1[0]=(&w30);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #34: @31 = linear(@32, @62) */
  arg1[0]=(&w32);
  arg1[1]=w62;
  res1[0]=(&w31);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #35: @32 = linear(@33, @62) */
  arg1[0]=(&w33);
  arg1[1]=w62;
  res1[0]=(&w32);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #36: @33 = linear(@34, @62) */
  arg1[0]=(&w34);
  arg1[1]=w62;
  res1[0]=(&w33);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #37: @34 = linear(@35, @62) */
  arg1[0]=(&w35);
  arg1[1]=w62;
  res1[0]=(&w34);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #38: @35 = linear(@36, @62) */
  arg1[0]=(&w36);
  arg1[1]=w62;
  res1[0]=(&w35);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #39: @36 = linear(@37, @62) */
  arg1[0]=(&w37);
  arg1[1]=w62;
  res1[0]=(&w36);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #40: @37 = linear(@38, @62) */
  arg1[0]=(&w38);
  arg1[1]=w62;
  res1[0]=(&w37);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #41: @38 = linear(@39, @62) */
  arg1[0]=(&w39);
  arg1[1]=w62;
  res1[0]=(&w38);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #42: @39 = linear(@40, @62) */
  arg1[0]=(&w40);
  arg1[1]=w62;
  res1[0]=(&w39);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #43: @40 = linear(@41, @62) */
  arg1[0]=(&w41);
  arg1[1]=w62;
  res1[0]=(&w40);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #44: @41 = linear(@42, @62) */
  arg1[0]=(&w42);
  arg1[1]=w62;
  res1[0]=(&w41);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #45: @42 = linear(@43, @62) */
  arg1[0]=(&w43);
  arg1[1]=w62;
  res1[0]=(&w42);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #46: @43 = linear(@44, @62) */
  arg1[0]=(&w44);
  arg1[1]=w62;
  res1[0]=(&w43);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #47: @44 = linear(@45, @62) */
  arg1[0]=(&w45);
  arg1[1]=w62;
  res1[0]=(&w44);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #48: @45 = linear(@46, @62) */
  arg1[0]=(&w46);
  arg1[1]=w62;
  res1[0]=(&w45);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #49: @46 = linear(@47, @62) */
  arg1[0]=(&w47);
  arg1[1]=w62;
  res1[0]=(&w46);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #50: @47 = linear(@48, @62) */
  arg1[0]=(&w48);
  arg1[1]=w62;
  res1[0]=(&w47);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #51: @48 = linear(@49, @62) */
  arg1[0]=(&w49);
  arg1[1]=w62;
  res1[0]=(&w48);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #52: @49 = linear(@50, @62) */
  arg1[0]=(&w50);
  arg1[1]=w62;
  res1[0]=(&w49);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #53: @50 = linear(@51, @62) */
  arg1[0]=(&w51);
  arg1[1]=w62;
  res1[0]=(&w50);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #54: @51 = linear(@52, @62) */
  arg1[0]=(&w52);
  arg1[1]=w62;
  res1[0]=(&w51);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #55: @52 = linear(@53, @62) */
  arg1[0]=(&w53);
  arg1[1]=w62;
  res1[0]=(&w52);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #56: @53 = linear(@54, @62) */
  arg1[0]=(&w54);
  arg1[1]=w62;
  res1[0]=(&w53);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #57: @54 = linear(@55, @62) */
  arg1[0]=(&w55);
  arg1[1]=w62;
  res1[0]=(&w54);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #58: @55 = linear(@56, @62) */
  arg1[0]=(&w56);
  arg1[1]=w62;
  res1[0]=(&w55);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #59: @56 = linear(@57, @62) */
  arg1[0]=(&w57);
  arg1[1]=w62;
  res1[0]=(&w56);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #60: @57 = linear(@58, @62) */
  arg1[0]=(&w58);
  arg1[1]=w62;
  res1[0]=(&w57);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #61: @58 = linear(@59, @62) */
  arg1[0]=(&w59);
  arg1[1]=w62;
  res1[0]=(&w58);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #62: @59 = linear(@60, @62) */
  arg1[0]=(&w60);
  arg1[1]=w62;
  res1[0]=(&w59);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #63: @60 = linear(@61, @62) */
  arg1[0]=(&w61);
  arg1[1]=w62;
  res1[0]=(&w60);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #64: @1 = horzcat(@63, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56, @57, @58, @59, @60) */
  rr=w1;
  *rr++ = w63;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w56;
  *rr++ = w57;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w60;
  /* #65: @63 = BSplineParametric(@0) */
  casadi_clear((&w63), 1);
  CASADI_PREFIX(nd_boor_eval)((&w63),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #66: output[0][0] = @63 */
  if (res[0]) res[0][0] = w63;
  return 0;
}

/* rockit_model_constr_h_e_fun:(i0[5],i1[],i2[],i3[66])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, *w2=w+154, w3, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[3][3] */
  casadi_copy(arg[3] ? arg[3]+6 : 0, 20, w2);
  /* #3: @3 = x(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @0 = (@0-@3) */
  w0 -= w3;
  /* #5: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #6: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #7: @2 = input[3][4] */
  casadi_copy(arg[3] ? arg[3]+26 : 0, 20, w2);
  /* #8: @4 = y(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @3 = (@3-@4) */
  w3 -= w4;
  /* #10: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #11: @0 = (@0+@3) */
  w0 += w3;
  /* #12: @2 = input[3][5] */
  casadi_copy(arg[3] ? arg[3]+46 : 0, 20, w2);
  /* #13: @3 = r(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w3);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #14: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #15: @0 = (@0-@3) */
  w0 -= w3;
  /* #16: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_constr_h_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_constr_h_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_constr_h_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 68;
  if (sz_res) *sz_res = 63;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 176;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
