/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockitmmap_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

#ifndef casadi_inf
  #define casadi_inf INFINITY
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[70] = {66, 1, 0, 66, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* rockitmmap:(p[66],t)->(lbx[0],ubx[0],lbu[3],ubu[3],C[0],D[0],lg[0],ug[0],lh,uh,lh_e,uh_e,lbx_e,ubx_e,C_e[0],lg_e[0],ug_e[0],lbx_0[5],ubx_0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+2;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: output[2][0] = @0 */
  if (res[2]) res[2][0] = w0;
  /* #2: @0 = -3.14159 */
  w0 = -3.1415926535897931e+00;
  /* #3: output[2][1] = @0 */
  if (res[2]) res[2][1] = w0;
  /* #4: @0 = 0 */
  w0 = 0.;
  /* #5: output[2][2] = @0 */
  if (res[2]) res[2][2] = w0;
  /* #6: @0 = 1 */
  w0 = 1.;
  /* #7: output[3][0] = @0 */
  if (res[3]) res[3][0] = w0;
  /* #8: @0 = 3.14159 */
  w0 = 3.1415926535897931e+00;
  /* #9: output[3][1] = @0 */
  if (res[3]) res[3][1] = w0;
  /* #10: @0 = inf */
  w0 = casadi_inf;
  /* #11: output[3][2] = @0 */
  if (res[3]) res[3][2] = w0;
  /* #12: @0 = -inf */
  w0 = -casadi_inf;
  /* #13: output[8][0] = @0 */
  if (res[8]) res[8][0] = w0;
  /* #14: @1 = 0 */
  w1 = 0.;
  /* #15: output[9][0] = @1 */
  if (res[9]) res[9][0] = w1;
  /* #16: output[10][0] = @0 */
  if (res[10]) res[10][0] = w0;
  /* #17: output[11][0] = @1 */
  if (res[11]) res[11][0] = w1;
  /* #18: @1 = -inf */
  w1 = -casadi_inf;
  /* #19: output[12][0] = @1 */
  if (res[12]) res[12][0] = w1;
  /* #20: @1 = 1 */
  w1 = 1.;
  /* #21: output[13][0] = @1 */
  if (res[13]) res[13][0] = w1;
  /* #22: @2 = input[0][0] */
  casadi_copy(arg[0], 4, w2);
  /* #23: output[17][0] = @2 */
  casadi_copy(w2, 4, res[17]);
  /* #24: @1 = 0 */
  w1 = 0.;
  /* #25: output[17][1] = @1 */
  if (res[17]) res[17][4] = w1;
  /* #26: output[18][0] = @2 */
  casadi_copy(w2, 4, res[18]);
  /* #27: @1 = 0 */
  w1 = 0.;
  /* #28: output[18][1] = @1 */
  if (res[18]) res[18][4] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int rockitmmap(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockitmmap_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockitmmap_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockitmmap_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockitmmap_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockitmmap_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockitmmap_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockitmmap_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockitmmap_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int rockitmmap_n_out(void) { return 19;}

CASADI_SYMBOL_EXPORT casadi_real rockitmmap_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockitmmap_name_in(casadi_int i){
  switch (i) {
    case 0: return "p";
    case 1: return "t";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockitmmap_name_out(casadi_int i){
  switch (i) {
    case 0: return "lbx";
    case 1: return "ubx";
    case 2: return "lbu";
    case 3: return "ubu";
    case 4: return "C";
    case 5: return "D";
    case 6: return "lg";
    case 7: return "ug";
    case 8: return "lh";
    case 9: return "uh";
    case 10: return "lh_e";
    case 11: return "uh_e";
    case 12: return "lbx_e";
    case 13: return "ubx_e";
    case 14: return "C_e";
    case 15: return "lg_e";
    case 16: return "ug_e";
    case 17: return "lbx_0";
    case 18: return "ubx_0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockitmmap_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockitmmap_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    case 7: return casadi_s2;
    case 8: return casadi_s1;
    case 9: return casadi_s1;
    case 10: return casadi_s1;
    case 11: return casadi_s1;
    case 12: return casadi_s1;
    case 13: return casadi_s1;
    case 14: return casadi_s2;
    case 15: return casadi_s2;
    case 16: return casadi_s2;
    case 17: return casadi_s4;
    case 18: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockitmmap_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 20;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
