/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[70] = {66, 1, 0, 66, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65};

/* ode:(x[5],u[3],z[0],p[66],t[1x1,0nz])->(ode[5],alg[0],quad[0]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @0 = (@0*@1) */
  w0 *= w1;
  /* #7: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #8: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #9: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #10: @0 = input[1][2] */
  w0 = arg[1] ? arg[1][2] : 0;
  /* #11: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #12: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #13: @1 = input[3][1] */
  w1 = arg[3] ? arg[3][4] : 0;
  /* #14: @0 = (@0-@1) */
  w0 -= w1;
  /* #15: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #16: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #17: @2 = input[3][2] */
  w2 = arg[3] ? arg[3][5] : 0;
  /* #18: @1 = (@1-@2) */
  w1 -= w2;
  /* #19: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #20: @0 = (@0+@1) */
  w0 += w1;
  /* #21: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  return 0;
}

/* F:(x0[5],u[3],t0,DT,p[66])->(xf[5],poly_coeff[5x5],qf[0],zf[0],poly_coeff_z[]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr;
  const casadi_real **arg1=arg+5, *cr, *cs;
  casadi_real *w0=w+3, w1, w2, *w3=w+10, *w5=w+13, *w7=w+79, w8, *w9=w+85, *w10=w+90, *w11=w+95, *w12=w+100, *w13=w+105;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @2 = 6 */
  w2 = 6.;
  /* #3: @2 = (@1/@2) */
  w2  = (w1/w2);
  /* #4: @3 = input[1][0] */
  casadi_copy(arg[1], 3, w3);
  /* #5: @4 = 0x1 */
  /* #6: @5 = input[4][0] */
  casadi_copy(arg[4], 66, w5);
  /* #7: @6 = 00 */
  /* #8: {@7, NULL, NULL} = ode(@0, @3, @4, @5, @6) */
  arg1[0]=w0;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w7;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @8 = 2 */
  w8 = 2.;
  /* #10: @8 = (@1/@8) */
  w8  = (w1/w8);
  /* #11: @9 = (@8*@7) */
  for (i=0, rr=w9, cs=w7; i<5; ++i) (*rr++)  = (w8*(*cs++));
  /* #12: @9 = (@0+@9) */
  for (i=0, rr=w9, cr=w0, cs=w9; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #13: @4 = 0x1 */
  /* #14: @6 = 00 */
  /* #15: {@10, NULL, NULL} = ode(@9, @3, @4, @5, @6) */
  arg1[0]=w9;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w10;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @9 = (2.*@10) */
  for (i=0, rr=w9, cs=w10; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #17: @9 = (@7+@9) */
  for (i=0, rr=w9, cr=w7, cs=w9; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #18: @8 = 2 */
  w8 = 2.;
  /* #19: @8 = (@1/@8) */
  w8  = (w1/w8);
  /* #20: @11 = (@8*@10) */
  for (i=0, rr=w11, cs=w10; i<5; ++i) (*rr++)  = (w8*(*cs++));
  /* #21: @11 = (@0+@11) */
  for (i=0, rr=w11, cr=w0, cs=w11; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #22: @4 = 0x1 */
  /* #23: @6 = 00 */
  /* #24: {@12, NULL, NULL} = ode(@11, @3, @4, @5, @6) */
  arg1[0]=w11;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w12;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #25: @11 = (2.*@12) */
  for (i=0, rr=w11, cs=w12; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #26: @9 = (@9+@11) */
  for (i=0, rr=w9, cs=w11; i<5; ++i) (*rr++) += (*cs++);
  /* #27: @11 = (@1*@12) */
  for (i=0, rr=w11, cs=w12; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #28: @11 = (@0+@11) */
  for (i=0, rr=w11, cr=w0, cs=w11; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #29: @4 = 0x1 */
  /* #30: @6 = 00 */
  /* #31: {@13, NULL, NULL} = ode(@11, @3, @4, @5, @6) */
  arg1[0]=w11;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w13;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #32: @9 = (@9+@13) */
  for (i=0, rr=w9, cs=w13; i<5; ++i) (*rr++) += (*cs++);
  /* #33: @9 = (@2*@9) */
  for (i=0, rr=w9, cs=w9; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #34: @9 = (@0+@9) */
  for (i=0, rr=w9, cr=w0, cs=w9; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #35: output[0][0] = @9 */
  casadi_copy(w9, 5, res[0]);
  /* #36: output[1][0] = @0 */
  casadi_copy(w0, 5, res[1]);
  /* #37: output[1][1] = @7 */
  if (res[1]) casadi_copy(w7, 5, res[1]+5);
  /* #38: @2 = 2 */
  w2 = 2.;
  /* #39: @2 = (@2/@1) */
  w2 /= w1;
  /* #40: @0 = (@10-@7) */
  for (i=0, rr=w0, cr=w10, cs=w7; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #41: @0 = (@2*@0) */
  for (i=0, rr=w0, cs=w0; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #42: @2 = 2 */
  w2 = 2.;
  /* #43: @0 = (@0/@2) */
  for (i=0, rr=w0; i<5; ++i) (*rr++) /= w2;
  /* #44: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 5, res[1]+10);
  /* #45: @2 = 4 */
  w2 = 4.;
  /* #46: @8 = sq(@1) */
  w8 = casadi_sq( w1 );
  /* #47: @2 = (@2/@8) */
  w2 /= w8;
  /* #48: @10 = (@12-@10) */
  for (i=0, rr=w10, cr=w12, cs=w10; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #49: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #50: @2 = 6 */
  w2 = 6.;
  /* #51: @10 = (@10/@2) */
  for (i=0, rr=w10; i<5; ++i) (*rr++) /= w2;
  /* #52: output[1][3] = @10 */
  if (res[1]) casadi_copy(w10, 5, res[1]+15);
  /* #53: @2 = 4 */
  w2 = 4.;
  /* #54: @12 = (2.*@12) */
  for (i=0, rr=w12, cs=w12; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #55: @13 = (@13-@12) */
  for (i=0, rr=w13, cs=w12; i<5; ++i) (*rr++) -= (*cs++);
  /* #56: @13 = (@13+@7) */
  for (i=0, rr=w13, cs=w7; i<5; ++i) (*rr++) += (*cs++);
  /* #57: @13 = (@2*@13) */
  for (i=0, rr=w13, cs=w13; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #58: @2 = 3 */
  w2 = 3.;
  /* #59: @1 = pow(@1,@2) */
  w1  = pow(w1,w2);
  /* #60: @13 = (@13/@1) */
  for (i=0, rr=w13; i<5; ++i) (*rr++) /= w1;
  /* #61: @1 = 24 */
  w1 = 24.;
  /* #62: @13 = (@13/@1) */
  for (i=0, rr=w13; i<5; ++i) (*rr++) /= w1;
  /* #63: output[1][4] = @13 */
  if (res[1]) casadi_copy(w13, 5, res[1]+20);
  return 0;
}

/* F:(x0[5],u[3],T,t0,p[66])->(xf[5],Xi[5x2],poly_coeff[5x5],qf[0],zf[0],Zi[0],poly_coeff_z[]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+7;
  const casadi_real **arg1=arg+5;
  casadi_real *w0=w+110, *w1=w+115, w2, w3, *w4=w+120, *w5=w+186, *w6=w+191;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w1);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #4: @4 = input[4][0] */
  casadi_copy(arg[4], 66, w4);
  /* #5: {@5, @6, NULL, NULL, NULL} = F(@0, @1, @2, @3, @4) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=(&w2);
  arg1[3]=(&w3);
  arg1[4]=w4;
  res1[0]=w5;
  res1[1]=w6;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][0] = @5 */
  casadi_copy(w5, 5, res[0]);
  /* #7: output[1][0] = @0 */
  casadi_copy(w0, 5, res[1]);
  /* #8: output[1][1] = @5 */
  if (res[1]) casadi_copy(w5, 5, res[1]+5);
  /* #9: output[2][0] = @6 */
  casadi_copy(w6, 25, res[2]);
  return 0;
}

/* rockit_model_dyn_disc_phi_fun:(i0[5],i1[3],i2[66])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+221, *w6=w+226, *w7=w+229, *w8=w+233, *w9=w+253, *w10=w+273, *w11=w+293, *w12=w+359;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = vertcat(@0, @1, @2, @3, @4) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #6: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #7: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #8: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #9: @6 = vertcat(@0, @1, @2) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  /* #10: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #11: @1 = 0 */
  w1 = 0.;
  /* #12: @7 = input[2][0] */
  casadi_copy(arg[2], 4, w7);
  /* #13: @2 = input[2][1] */
  w2 = arg[2] ? arg[2][4] : 0;
  /* #14: @3 = input[2][2] */
  w3 = arg[2] ? arg[2][5] : 0;
  /* #15: @8 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 20, w8);
  /* #16: @9 = input[2][4] */
  casadi_copy(arg[2] ? arg[2]+26 : 0, 20, w9);
  /* #17: @10 = input[2][5] */
  casadi_copy(arg[2] ? arg[2]+46 : 0, 20, w10);
  /* #18: @11 = vertcat(@7, @2, @3, @8, @9, @10) */
  rr=w11;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  *rr++ = w2;
  *rr++ = w3;
  for (i=0, cs=w8; i<20; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<20; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<20; ++i) *rr++ = *cs++;
  /* #19: {@12, NULL, NULL, NULL, NULL, NULL, NULL} = F(@5, @6, @0, @1, @11) */
  arg1[0]=w5;
  arg1[1]=w6;
  arg1[2]=(&w0);
  arg1[3]=(&w1);
  arg1[4]=w11;
  res1[0]=w12;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][0] = @12 */
  casadi_copy(w12, 5, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_dyn_disc_phi_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_dyn_disc_phi_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_dyn_disc_phi_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 364;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
