/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[14] = {5, 6, 0, 0, 1, 2, 3, 4, 5, 3, 0, 1, 2, 4};
static const casadi_int casadi_s1[12] = {3, 6, 0, 2, 3, 3, 3, 3, 3, 0, 2, 1};
static const casadi_int casadi_s2[4] = {0, 4, 10, 12};
static const casadi_int casadi_s3[5] = {1, 5, 8, 11, 13};
static const casadi_int casadi_s4[4] = {0, 1, 2, 4};
static const casadi_int casadi_s5[4] = {3, 7, 9, 16};
static const casadi_int casadi_s6[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[70] = {66, 1, 0, 66, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65};
static const casadi_int casadi_s9[26] = {8, 5, 0, 4, 8, 10, 12, 18, 0, 1, 3, 5, 0, 1, 4, 5, 1, 5, 2, 6, 0, 1, 3, 4, 5, 7};

/* ode:(x[5],u[3],z[0],p[66],t[1x1,0nz])->(ode[5],alg[0],quad[0]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @0 = (@0*@1) */
  w0 *= w1;
  /* #7: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #8: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #9: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #10: @0 = input[1][2] */
  w0 = arg[1] ? arg[1][2] : 0;
  /* #11: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #12: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #13: @1 = input[3][1] */
  w1 = arg[3] ? arg[3][4] : 0;
  /* #14: @0 = (@0-@1) */
  w0 -= w1;
  /* #15: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #16: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #17: @2 = input[3][2] */
  w2 = arg[3] ? arg[3][5] : 0;
  /* #18: @1 = (@1-@2) */
  w1 -= w2;
  /* #19: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #20: @0 = (@0+@1) */
  w0 += w1;
  /* #21: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  return 0;
}

/* F:(x0[5],u[3],t0,DT,p[66])->(xf[5],poly_coeff[5x5],qf[0],zf[0],poly_coeff_z[]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr;
  const casadi_real **arg1=arg+5, *cr, *cs;
  casadi_real *w0=w+3, w1, w2, *w3=w+10, *w5=w+13, *w7=w+79, w8, *w9=w+85, *w10=w+90, *w11=w+95, *w12=w+100, *w13=w+105;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @2 = 6 */
  w2 = 6.;
  /* #3: @2 = (@1/@2) */
  w2  = (w1/w2);
  /* #4: @3 = input[1][0] */
  casadi_copy(arg[1], 3, w3);
  /* #5: @4 = 0x1 */
  /* #6: @5 = input[4][0] */
  casadi_copy(arg[4], 66, w5);
  /* #7: @6 = 00 */
  /* #8: {@7, NULL, NULL} = ode(@0, @3, @4, @5, @6) */
  arg1[0]=w0;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w7;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @8 = 2 */
  w8 = 2.;
  /* #10: @8 = (@1/@8) */
  w8  = (w1/w8);
  /* #11: @9 = (@8*@7) */
  for (i=0, rr=w9, cs=w7; i<5; ++i) (*rr++)  = (w8*(*cs++));
  /* #12: @9 = (@0+@9) */
  for (i=0, rr=w9, cr=w0, cs=w9; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #13: @4 = 0x1 */
  /* #14: @6 = 00 */
  /* #15: {@10, NULL, NULL} = ode(@9, @3, @4, @5, @6) */
  arg1[0]=w9;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w10;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @9 = (2.*@10) */
  for (i=0, rr=w9, cs=w10; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #17: @9 = (@7+@9) */
  for (i=0, rr=w9, cr=w7, cs=w9; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #18: @8 = 2 */
  w8 = 2.;
  /* #19: @8 = (@1/@8) */
  w8  = (w1/w8);
  /* #20: @11 = (@8*@10) */
  for (i=0, rr=w11, cs=w10; i<5; ++i) (*rr++)  = (w8*(*cs++));
  /* #21: @11 = (@0+@11) */
  for (i=0, rr=w11, cr=w0, cs=w11; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #22: @4 = 0x1 */
  /* #23: @6 = 00 */
  /* #24: {@12, NULL, NULL} = ode(@11, @3, @4, @5, @6) */
  arg1[0]=w11;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w12;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #25: @11 = (2.*@12) */
  for (i=0, rr=w11, cs=w12; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #26: @9 = (@9+@11) */
  for (i=0, rr=w9, cs=w11; i<5; ++i) (*rr++) += (*cs++);
  /* #27: @11 = (@1*@12) */
  for (i=0, rr=w11, cs=w12; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #28: @11 = (@0+@11) */
  for (i=0, rr=w11, cr=w0, cs=w11; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #29: @4 = 0x1 */
  /* #30: @6 = 00 */
  /* #31: {@13, NULL, NULL} = ode(@11, @3, @4, @5, @6) */
  arg1[0]=w11;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=w5;
  arg1[4]=0;
  res1[0]=w13;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #32: @9 = (@9+@13) */
  for (i=0, rr=w9, cs=w13; i<5; ++i) (*rr++) += (*cs++);
  /* #33: @9 = (@2*@9) */
  for (i=0, rr=w9, cs=w9; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #34: @9 = (@0+@9) */
  for (i=0, rr=w9, cr=w0, cs=w9; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #35: output[0][0] = @9 */
  casadi_copy(w9, 5, res[0]);
  /* #36: output[1][0] = @0 */
  casadi_copy(w0, 5, res[1]);
  /* #37: output[1][1] = @7 */
  if (res[1]) casadi_copy(w7, 5, res[1]+5);
  /* #38: @2 = 2 */
  w2 = 2.;
  /* #39: @2 = (@2/@1) */
  w2 /= w1;
  /* #40: @0 = (@10-@7) */
  for (i=0, rr=w0, cr=w10, cs=w7; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #41: @0 = (@2*@0) */
  for (i=0, rr=w0, cs=w0; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #42: @2 = 2 */
  w2 = 2.;
  /* #43: @0 = (@0/@2) */
  for (i=0, rr=w0; i<5; ++i) (*rr++) /= w2;
  /* #44: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 5, res[1]+10);
  /* #45: @2 = 4 */
  w2 = 4.;
  /* #46: @8 = sq(@1) */
  w8 = casadi_sq( w1 );
  /* #47: @2 = (@2/@8) */
  w2 /= w8;
  /* #48: @10 = (@12-@10) */
  for (i=0, rr=w10, cr=w12, cs=w10; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #49: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #50: @2 = 6 */
  w2 = 6.;
  /* #51: @10 = (@10/@2) */
  for (i=0, rr=w10; i<5; ++i) (*rr++) /= w2;
  /* #52: output[1][3] = @10 */
  if (res[1]) casadi_copy(w10, 5, res[1]+15);
  /* #53: @2 = 4 */
  w2 = 4.;
  /* #54: @12 = (2.*@12) */
  for (i=0, rr=w12, cs=w12; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #55: @13 = (@13-@12) */
  for (i=0, rr=w13, cs=w12; i<5; ++i) (*rr++) -= (*cs++);
  /* #56: @13 = (@13+@7) */
  for (i=0, rr=w13, cs=w7; i<5; ++i) (*rr++) += (*cs++);
  /* #57: @13 = (@2*@13) */
  for (i=0, rr=w13, cs=w13; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #58: @2 = 3 */
  w2 = 3.;
  /* #59: @1 = pow(@1,@2) */
  w1  = pow(w1,w2);
  /* #60: @13 = (@13/@1) */
  for (i=0, rr=w13; i<5; ++i) (*rr++) /= w1;
  /* #61: @1 = 24 */
  w1 = 24.;
  /* #62: @13 = (@13/@1) */
  for (i=0, rr=w13; i<5; ++i) (*rr++) /= w1;
  /* #63: output[1][4] = @13 */
  if (res[1]) casadi_copy(w13, 5, res[1]+20);
  return 0;
}

/* F:(x0[5],u[3],T,t0,p[66])->(xf[5],Xi[5x2],poly_coeff[5x5],qf[0],zf[0],Zi[0],poly_coeff_z[]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+7;
  const casadi_real **arg1=arg+5;
  casadi_real *w0=w+110, *w1=w+115, w2, w3, *w4=w+120, *w5=w+186, *w6=w+191;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w1);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #4: @4 = input[4][0] */
  casadi_copy(arg[4], 66, w4);
  /* #5: {@5, @6, NULL, NULL, NULL} = F(@0, @1, @2, @3, @4) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=(&w2);
  arg1[3]=(&w3);
  arg1[4]=w4;
  res1[0]=w5;
  res1[1]=w6;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][0] = @5 */
  casadi_copy(w5, 5, res[0]);
  /* #7: output[1][0] = @0 */
  casadi_copy(w0, 5, res[1]);
  /* #8: output[1][1] = @5 */
  if (res[1]) casadi_copy(w5, 5, res[1]+5);
  /* #9: output[2][0] = @6 */
  casadi_copy(w6, 25, res[2]);
  return 0;
}

/* fwd6_ode:(x[5],u[3],z[0],p[66],t[1x1,0nz],out_ode[5x1,0nz],out_alg[0],out_quad[0],fwd_x[5x6],fwd_u[3x6],fwd_z[0x6],fwd_p[66x6],fwd_t[1x6,0nz])->(fwd_ode[5x6],fwd_alg[0x6],fwd_quad[0x6]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+2, w3, w4, w5, w6, w7, w8, *w9=w+11, w10, w11, w12, w13, *w14=w+20, w15, w16, w17;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[9][0] */
  casadi_copy(arg[9], 3, w2);
  /* #3: {@3, @4, @5} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  /* #4: @6 = (@1*@3) */
  w6  = (w1*w3);
  /* #5: @7 = input[1][0] */
  w7 = arg[1] ? arg[1][0] : 0;
  /* #6: @8 = sin(@0) */
  w8 = sin( w0 );
  /* #7: @9 = input[8][0] */
  casadi_copy(arg[8], 5, w9);
  /* #8: {@10, @11, @12, NULL, NULL} = vertsplit(@9) */
  w10 = w9[0];
  w11 = w9[1];
  w12 = w9[2];
  /* #9: @13 = (@8*@12) */
  w13  = (w8*w12);
  /* #10: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #11: @6 = (@6-@13) */
  w6 -= w13;
  /* #12: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #13: @6 = sin(@0) */
  w6 = sin( w0 );
  /* #14: @3 = (@6*@3) */
  w3  = (w6*w3);
  /* #15: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #16: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #17: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #18: @3 = (@3+@12) */
  w3 += w12;
  /* #19: output[0][1] = @3 */
  if (res[0]) res[0][1] = w3;
  /* #20: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #21: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #22: @5 = input[0][0] */
  w5 = arg[0] ? arg[0][0] : 0;
  /* #23: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][4] : 0;
  /* #24: @5 = (@5-@4) */
  w5 -= w4;
  /* #25: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #26: @14 = input[11][0] */
  casadi_copy(arg[11], 66, w14);
  /* #27: {NULL, @4, @3, NULL, NULL, NULL} = vertsplit(@14) */
  w4 = w14[4];
  w3 = w14[5];
  /* #28: @10 = (@10-@4) */
  w10 -= w4;
  /* #29: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #30: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #31: @12 = input[3][2] */
  w12 = arg[3] ? arg[3][5] : 0;
  /* #32: @4 = (@4-@12) */
  w4 -= w12;
  /* #33: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #34: @11 = (@11-@3) */
  w11 -= w3;
  /* #35: @11 = (@4*@11) */
  w11  = (w4*w11);
  /* #36: @10 = (@10+@11) */
  w10 += w11;
  /* #37: output[0][4] = @10 */
  if (res[0]) res[0][4] = w10;
  /* #38: @2 = input[9][1] */
  casadi_copy(arg[9] ? arg[9]+3 : 0, 3, w2);
  /* #39: {@10, @11, @3} = vertsplit(@2) */
  w10 = w2[0];
  w11 = w2[1];
  w3 = w2[2];
  /* #40: @12 = (@1*@10) */
  w12  = (w1*w10);
  /* #41: @9 = input[8][1] */
  casadi_copy(arg[8] ? arg[8]+5 : 0, 5, w9);
  /* #42: {@13, @15, @16, NULL, NULL} = vertsplit(@9) */
  w13 = w9[0];
  w15 = w9[1];
  w16 = w9[2];
  /* #43: @17 = (@8*@16) */
  w17  = (w8*w16);
  /* #44: @17 = (@7*@17) */
  w17  = (w7*w17);
  /* #45: @12 = (@12-@17) */
  w12 -= w17;
  /* #46: output[0][5] = @12 */
  if (res[0]) res[0][5] = w12;
  /* #47: @10 = (@6*@10) */
  w10  = (w6*w10);
  /* #48: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #49: @16 = (@7*@16) */
  w16  = (w7*w16);
  /* #50: @10 = (@10+@16) */
  w10 += w16;
  /* #51: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #52: output[0][7] = @11 */
  if (res[0]) res[0][7] = w11;
  /* #53: output[0][8] = @3 */
  if (res[0]) res[0][8] = w3;
  /* #54: @14 = input[11][1] */
  casadi_copy(arg[11] ? arg[11]+66 : 0, 66, w14);
  /* #55: {NULL, @3, @11, NULL, NULL, NULL} = vertsplit(@14) */
  w3 = w14[4];
  w11 = w14[5];
  /* #56: @13 = (@13-@3) */
  w13 -= w3;
  /* #57: @13 = (@5*@13) */
  w13  = (w5*w13);
  /* #58: @15 = (@15-@11) */
  w15 -= w11;
  /* #59: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #60: @13 = (@13+@15) */
  w13 += w15;
  /* #61: output[0][9] = @13 */
  if (res[0]) res[0][9] = w13;
  /* #62: @2 = input[9][2] */
  casadi_copy(arg[9] ? arg[9]+6 : 0, 3, w2);
  /* #63: {@13, @15, @11} = vertsplit(@2) */
  w13 = w2[0];
  w15 = w2[1];
  w11 = w2[2];
  /* #64: @3 = (@1*@13) */
  w3  = (w1*w13);
  /* #65: @9 = input[8][2] */
  casadi_copy(arg[8] ? arg[8]+10 : 0, 5, w9);
  /* #66: {@10, @16, @12, NULL, NULL} = vertsplit(@9) */
  w10 = w9[0];
  w16 = w9[1];
  w12 = w9[2];
  /* #67: @17 = (@8*@12) */
  w17  = (w8*w12);
  /* #68: @17 = (@7*@17) */
  w17  = (w7*w17);
  /* #69: @3 = (@3-@17) */
  w3 -= w17;
  /* #70: output[0][10] = @3 */
  if (res[0]) res[0][10] = w3;
  /* #71: @13 = (@6*@13) */
  w13  = (w6*w13);
  /* #72: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #73: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #74: @13 = (@13+@12) */
  w13 += w12;
  /* #75: output[0][11] = @13 */
  if (res[0]) res[0][11] = w13;
  /* #76: output[0][12] = @15 */
  if (res[0]) res[0][12] = w15;
  /* #77: output[0][13] = @11 */
  if (res[0]) res[0][13] = w11;
  /* #78: @14 = input[11][2] */
  casadi_copy(arg[11] ? arg[11]+132 : 0, 66, w14);
  /* #79: {NULL, @11, @15, NULL, NULL, NULL} = vertsplit(@14) */
  w11 = w14[4];
  w15 = w14[5];
  /* #80: @10 = (@10-@11) */
  w10 -= w11;
  /* #81: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #82: @16 = (@16-@15) */
  w16 -= w15;
  /* #83: @16 = (@4*@16) */
  w16  = (w4*w16);
  /* #84: @10 = (@10+@16) */
  w10 += w16;
  /* #85: output[0][14] = @10 */
  if (res[0]) res[0][14] = w10;
  /* #86: @2 = input[9][3] */
  casadi_copy(arg[9] ? arg[9]+9 : 0, 3, w2);
  /* #87: {@10, @16, @15} = vertsplit(@2) */
  w10 = w2[0];
  w16 = w2[1];
  w15 = w2[2];
  /* #88: @11 = (@1*@10) */
  w11  = (w1*w10);
  /* #89: @9 = input[8][3] */
  casadi_copy(arg[8] ? arg[8]+15 : 0, 5, w9);
  /* #90: {@13, @12, @3, NULL, NULL} = vertsplit(@9) */
  w13 = w9[0];
  w12 = w9[1];
  w3 = w9[2];
  /* #91: @17 = (@8*@3) */
  w17  = (w8*w3);
  /* #92: @17 = (@7*@17) */
  w17  = (w7*w17);
  /* #93: @11 = (@11-@17) */
  w11 -= w17;
  /* #94: output[0][15] = @11 */
  if (res[0]) res[0][15] = w11;
  /* #95: @10 = (@6*@10) */
  w10  = (w6*w10);
  /* #96: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #97: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #98: @10 = (@10+@3) */
  w10 += w3;
  /* #99: output[0][16] = @10 */
  if (res[0]) res[0][16] = w10;
  /* #100: output[0][17] = @16 */
  if (res[0]) res[0][17] = w16;
  /* #101: output[0][18] = @15 */
  if (res[0]) res[0][18] = w15;
  /* #102: @14 = input[11][3] */
  casadi_copy(arg[11] ? arg[11]+198 : 0, 66, w14);
  /* #103: {NULL, @15, @16, NULL, NULL, NULL} = vertsplit(@14) */
  w15 = w14[4];
  w16 = w14[5];
  /* #104: @13 = (@13-@15) */
  w13 -= w15;
  /* #105: @13 = (@5*@13) */
  w13  = (w5*w13);
  /* #106: @12 = (@12-@16) */
  w12 -= w16;
  /* #107: @12 = (@4*@12) */
  w12  = (w4*w12);
  /* #108: @13 = (@13+@12) */
  w13 += w12;
  /* #109: output[0][19] = @13 */
  if (res[0]) res[0][19] = w13;
  /* #110: @2 = input[9][4] */
  casadi_copy(arg[9] ? arg[9]+12 : 0, 3, w2);
  /* #111: {@13, @12, @16} = vertsplit(@2) */
  w13 = w2[0];
  w12 = w2[1];
  w16 = w2[2];
  /* #112: @15 = (@1*@13) */
  w15  = (w1*w13);
  /* #113: @9 = input[8][4] */
  casadi_copy(arg[8] ? arg[8]+20 : 0, 5, w9);
  /* #114: {@10, @3, @11, NULL, NULL} = vertsplit(@9) */
  w10 = w9[0];
  w3 = w9[1];
  w11 = w9[2];
  /* #115: @17 = (@8*@11) */
  w17  = (w8*w11);
  /* #116: @17 = (@7*@17) */
  w17  = (w7*w17);
  /* #117: @15 = (@15-@17) */
  w15 -= w17;
  /* #118: output[0][20] = @15 */
  if (res[0]) res[0][20] = w15;
  /* #119: @13 = (@6*@13) */
  w13  = (w6*w13);
  /* #120: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #121: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #122: @13 = (@13+@11) */
  w13 += w11;
  /* #123: output[0][21] = @13 */
  if (res[0]) res[0][21] = w13;
  /* #124: output[0][22] = @12 */
  if (res[0]) res[0][22] = w12;
  /* #125: output[0][23] = @16 */
  if (res[0]) res[0][23] = w16;
  /* #126: @14 = input[11][4] */
  casadi_copy(arg[11] ? arg[11]+264 : 0, 66, w14);
  /* #127: {NULL, @16, @12, NULL, NULL, NULL} = vertsplit(@14) */
  w16 = w14[4];
  w12 = w14[5];
  /* #128: @10 = (@10-@16) */
  w10 -= w16;
  /* #129: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #130: @3 = (@3-@12) */
  w3 -= w12;
  /* #131: @3 = (@4*@3) */
  w3  = (w4*w3);
  /* #132: @10 = (@10+@3) */
  w10 += w3;
  /* #133: output[0][24] = @10 */
  if (res[0]) res[0][24] = w10;
  /* #134: @2 = input[9][5] */
  casadi_copy(arg[9] ? arg[9]+15 : 0, 3, w2);
  /* #135: {@10, @3, @12} = vertsplit(@2) */
  w10 = w2[0];
  w3 = w2[1];
  w12 = w2[2];
  /* #136: @1 = (@1*@10) */
  w1 *= w10;
  /* #137: @9 = input[8][5] */
  casadi_copy(arg[8] ? arg[8]+25 : 0, 5, w9);
  /* #138: {@16, @13, @11, NULL, NULL} = vertsplit(@9) */
  w16 = w9[0];
  w13 = w9[1];
  w11 = w9[2];
  /* #139: @8 = (@8*@11) */
  w8 *= w11;
  /* #140: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #141: @1 = (@1-@8) */
  w1 -= w8;
  /* #142: output[0][25] = @1 */
  if (res[0]) res[0][25] = w1;
  /* #143: @6 = (@6*@10) */
  w6 *= w10;
  /* #144: @0 = (@0*@11) */
  w0 *= w11;
  /* #145: @7 = (@7*@0) */
  w7 *= w0;
  /* #146: @6 = (@6+@7) */
  w6 += w7;
  /* #147: output[0][26] = @6 */
  if (res[0]) res[0][26] = w6;
  /* #148: output[0][27] = @3 */
  if (res[0]) res[0][27] = w3;
  /* #149: output[0][28] = @12 */
  if (res[0]) res[0][28] = w12;
  /* #150: @14 = input[11][5] */
  casadi_copy(arg[11] ? arg[11]+330 : 0, 66, w14);
  /* #151: {NULL, @12, @3, NULL, NULL, NULL} = vertsplit(@14) */
  w12 = w14[4];
  w3 = w14[5];
  /* #152: @16 = (@16-@12) */
  w16 -= w12;
  /* #153: @5 = (@5*@16) */
  w5 *= w16;
  /* #154: @13 = (@13-@3) */
  w13 -= w3;
  /* #155: @4 = (@4*@13) */
  w4 *= w13;
  /* #156: @5 = (@5+@4) */
  w5 += w4;
  /* #157: output[0][29] = @5 */
  if (res[0]) res[0][29] = w5;
  return 0;
}

/* fwd6_F:(x0[5],u[3],t0,DT,p[66],out_xf[5x1,0nz],out_poly_coeff[5x5,0nz],out_qf[0],out_zf[0],out_poly_coeff_z[],fwd_x0[5x6],fwd_u[3x6],fwd_t0[1x6],fwd_DT[1x6],fwd_p[66x6])->(fwd_xf[5x6],fwd_poly_coeff[5x30],fwd_qf[0x6],fwd_zf[0x6],fwd_poly_coeff_z[]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr;
  const casadi_real **arg1=arg+15, *cr, *cs;
  casadi_real *w0=w+89, *w1=w+94, *w2=w+99, *w4=w+102, *w6=w+168, w9, w10, *w11=w+175, *w14=w+180, *w17=w+185, w18, *w19=w+191, *w22=w+196, *w25=w+201, *w28=w+206, w31, w32, w33, *w34=w+214, *w36=w+219, *w37=w+224, *w38=w+229, *w39=w+234, *w40=w+239, *w41=w+244, *w42=w+274, *w43=w+277, *w44=w+280, *w45=w+283, *w46=w+286, *w47=w+289, *w48=w+292, *w50=w+310, *w51=w+376, *w52=w+442, *w53=w+508, *w54=w+574, *w55=w+640, *w56=w+706, *w58=w+1102, *w59=w+1132, *w60=w+1137, *w61=w+1142, *w62=w+1147, *w63=w+1152, w64, w65, *w66=w+1159, *w67=w+1164, w68, *w69=w+1170, w70, *w71=w+1176, w72, *w73=w+1182, w74, *w75=w+1188, *w76=w+1193, *w77=w+1198, *w78=w+1203, *w79=w+1208, *w80=w+1213, *w81=w+1218, *w82=w+1223, *w83=w+1228, *w84=w+1233, *w85=w+1238, *w86=w+1243, *w87=w+1248, w88, w89, w90, w91, w92, w93;
  /* #0: @0 = input[10][0] */
  casadi_copy(arg[10], 5, w0);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 5, w1);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 3, w2);
  /* #3: @3 = 0x1 */
  /* #4: @4 = input[4][0] */
  casadi_copy(arg[4], 66, w4);
  /* #5: @5 = 00 */
  /* #6: {@6, @7, @8} = ode(@1, @2, @3, @4, @5) */
  arg1[0]=w1;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  res1[0]=w6;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #7: @9 = input[3][0] */
  w9 = arg[3] ? arg[3][0] : 0;
  /* #8: @10 = 2 */
  w10 = 2.;
  /* #9: @10 = (@9/@10) */
  w10  = (w9/w10);
  /* #10: @11 = (@10*@6) */
  for (i=0, rr=w11, cs=w6; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #11: @11 = (@1+@11) */
  for (i=0, rr=w11, cr=w1, cs=w11; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #12: @12 = 0x1 */
  /* #13: @13 = 00 */
  /* #14: {@14, @15, @16} = ode(@11, @2, @12, @4, @13) */
  arg1[0]=w11;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  res1[0]=w14;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #15: @17 = (2.*@14) */
  for (i=0, rr=w17, cs=w14; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #16: @17 = (@6+@17) */
  for (i=0, rr=w17, cr=w6, cs=w17; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #17: @18 = 2 */
  w18 = 2.;
  /* #18: @18 = (@9/@18) */
  w18  = (w9/w18);
  /* #19: @19 = (@18*@14) */
  for (i=0, rr=w19, cs=w14; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #20: @19 = (@1+@19) */
  for (i=0, rr=w19, cr=w1, cs=w19; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #21: @20 = 0x1 */
  /* #22: @21 = 00 */
  /* #23: {@22, @23, @24} = ode(@19, @2, @20, @4, @21) */
  arg1[0]=w19;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  res1[0]=w22;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #24: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #25: @17 = (@17+@25) */
  for (i=0, rr=w17, cs=w25; i<5; ++i) (*rr++) += (*cs++);
  /* #26: @25 = (@9*@22) */
  for (i=0, rr=w25, cs=w22; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #27: @25 = (@1+@25) */
  for (i=0, rr=w25, cr=w1, cs=w25; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #28: @26 = 0x1 */
  /* #29: @27 = 00 */
  /* #30: {@28, @29, @30} = ode(@25, @2, @26, @4, @27) */
  arg1[0]=w25;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  res1[0]=w28;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #31: @17 = (@17+@28) */
  for (i=0, rr=w17, cs=w28; i<5; ++i) (*rr++) += (*cs++);
  /* #32: @31 = 0.166667 */
  w31 = 1.6666666666666666e-01;
  /* #33: @32 = input[13][0] */
  w32 = arg[13] ? arg[13][0] : 0;
  /* #34: @33 = (@31*@32) */
  w33  = (w31*w32);
  /* #35: @34 = (@17*@33) */
  for (i=0, rr=w34, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w33);
  /* #36: @33 = 6 */
  w33 = 6.;
  /* #37: @33 = (@9/@33) */
  w33  = (w9/w33);
  /* #38: @35 = zeros(5x1,0nz) */
  /* #39: @36 = input[10][1] */
  casadi_copy(arg[10] ? arg[10]+5 : 0, 5, w36);
  /* #40: @37 = input[10][2] */
  casadi_copy(arg[10] ? arg[10]+10 : 0, 5, w37);
  /* #41: @38 = input[10][3] */
  casadi_copy(arg[10] ? arg[10]+15 : 0, 5, w38);
  /* #42: @39 = input[10][4] */
  casadi_copy(arg[10] ? arg[10]+20 : 0, 5, w39);
  /* #43: @40 = input[10][5] */
  casadi_copy(arg[10] ? arg[10]+25 : 0, 5, w40);
  /* #44: @41 = horzcat(@0, @36, @37, @38, @39, @40) */
  rr=w41;
  for (i=0, cs=w0; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<5; ++i) *rr++ = *cs++;
  /* #45: @42 = input[11][0] */
  casadi_copy(arg[11], 3, w42);
  /* #46: @43 = input[11][1] */
  casadi_copy(arg[11] ? arg[11]+3 : 0, 3, w43);
  /* #47: @44 = input[11][2] */
  casadi_copy(arg[11] ? arg[11]+6 : 0, 3, w44);
  /* #48: @45 = input[11][3] */
  casadi_copy(arg[11] ? arg[11]+9 : 0, 3, w45);
  /* #49: @46 = input[11][4] */
  casadi_copy(arg[11] ? arg[11]+12 : 0, 3, w46);
  /* #50: @47 = input[11][5] */
  casadi_copy(arg[11] ? arg[11]+15 : 0, 3, w47);
  /* #51: @48 = horzcat(@42, @43, @44, @45, @46, @47) */
  rr=w48;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  /* #52: @49 = 0x6 */
  /* #53: @50 = input[14][0] */
  casadi_copy(arg[14], 66, w50);
  /* #54: @51 = input[14][1] */
  casadi_copy(arg[14] ? arg[14]+66 : 0, 66, w51);
  /* #55: @52 = input[14][2] */
  casadi_copy(arg[14] ? arg[14]+132 : 0, 66, w52);
  /* #56: @53 = input[14][3] */
  casadi_copy(arg[14] ? arg[14]+198 : 0, 66, w53);
  /* #57: @54 = input[14][4] */
  casadi_copy(arg[14] ? arg[14]+264 : 0, 66, w54);
  /* #58: @55 = input[14][5] */
  casadi_copy(arg[14] ? arg[14]+330 : 0, 66, w55);
  /* #59: @56 = horzcat(@50, @51, @52, @53, @54, @55) */
  rr=w56;
  for (i=0, cs=w50; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<66; ++i) *rr++ = *cs++;
  /* #60: @57 = zeros(1x6,0nz) */
  /* #61: {@58, NULL, NULL} = fwd6_ode(@1, @2, @3, @4, @5, @35, @7, @8, @41, @48, @49, @56, @57) */
  arg1[0]=w1;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w41;
  arg1[9]=w48;
  arg1[10]=0;
  arg1[11]=w56;
  arg1[12]=0;
  res1[0]=w58;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #62: {@1, @59, @60, @61, @62, @63} = horzsplit(@58) */
  casadi_copy(w58, 5, w1);
  casadi_copy(w58+5, 5, w59);
  casadi_copy(w58+10, 5, w60);
  casadi_copy(w58+15, 5, w61);
  casadi_copy(w58+20, 5, w62);
  casadi_copy(w58+25, 5, w63);
  /* #63: @3 = zeros(5x1,0nz) */
  /* #64: @64 = 0.5 */
  w64 = 5.0000000000000000e-01;
  /* #65: @65 = (@64*@32) */
  w65  = (w64*w32);
  /* #66: @66 = (@6*@65) */
  for (i=0, rr=w66, cr=w6; i<5; ++i) (*rr++)  = ((*cr++)*w65);
  /* #67: @67 = (@10*@1) */
  for (i=0, rr=w67, cs=w1; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #68: @66 = (@66+@67) */
  for (i=0, rr=w66, cs=w67; i<5; ++i) (*rr++) += (*cs++);
  /* #69: @66 = (@0+@66) */
  for (i=0, rr=w66, cr=w0, cs=w66; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #70: @65 = input[13][1] */
  w65 = arg[13] ? arg[13][1] : 0;
  /* #71: @68 = (@64*@65) */
  w68  = (w64*w65);
  /* #72: @67 = (@6*@68) */
  for (i=0, rr=w67, cr=w6; i<5; ++i) (*rr++)  = ((*cr++)*w68);
  /* #73: @69 = (@10*@59) */
  for (i=0, rr=w69, cs=w59; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #74: @67 = (@67+@69) */
  for (i=0, rr=w67, cs=w69; i<5; ++i) (*rr++) += (*cs++);
  /* #75: @67 = (@36+@67) */
  for (i=0, rr=w67, cr=w36, cs=w67; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #76: @68 = input[13][2] */
  w68 = arg[13] ? arg[13][2] : 0;
  /* #77: @70 = (@64*@68) */
  w70  = (w64*w68);
  /* #78: @69 = (@6*@70) */
  for (i=0, rr=w69, cr=w6; i<5; ++i) (*rr++)  = ((*cr++)*w70);
  /* #79: @71 = (@10*@60) */
  for (i=0, rr=w71, cs=w60; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #80: @69 = (@69+@71) */
  for (i=0, rr=w69, cs=w71; i<5; ++i) (*rr++) += (*cs++);
  /* #81: @69 = (@37+@69) */
  for (i=0, rr=w69, cr=w37, cs=w69; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #82: @70 = input[13][3] */
  w70 = arg[13] ? arg[13][3] : 0;
  /* #83: @72 = (@64*@70) */
  w72  = (w64*w70);
  /* #84: @71 = (@6*@72) */
  for (i=0, rr=w71, cr=w6; i<5; ++i) (*rr++)  = ((*cr++)*w72);
  /* #85: @73 = (@10*@61) */
  for (i=0, rr=w73, cs=w61; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #86: @71 = (@71+@73) */
  for (i=0, rr=w71, cs=w73; i<5; ++i) (*rr++) += (*cs++);
  /* #87: @71 = (@38+@71) */
  for (i=0, rr=w71, cr=w38, cs=w71; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #88: @72 = input[13][4] */
  w72 = arg[13] ? arg[13][4] : 0;
  /* #89: @74 = (@64*@72) */
  w74  = (w64*w72);
  /* #90: @73 = (@6*@74) */
  for (i=0, rr=w73, cr=w6; i<5; ++i) (*rr++)  = ((*cr++)*w74);
  /* #91: @75 = (@10*@62) */
  for (i=0, rr=w75, cs=w62; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #92: @73 = (@73+@75) */
  for (i=0, rr=w73, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #93: @73 = (@39+@73) */
  for (i=0, rr=w73, cr=w39, cs=w73; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #94: @74 = input[13][5] */
  w74 = arg[13] ? arg[13][5] : 0;
  /* #95: @64 = (@64*@74) */
  w64 *= w74;
  /* #96: @75 = (@6*@64) */
  for (i=0, rr=w75, cr=w6; i<5; ++i) (*rr++)  = ((*cr++)*w64);
  /* #97: @76 = (@10*@63) */
  for (i=0, rr=w76, cs=w63; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #98: @75 = (@75+@76) */
  for (i=0, rr=w75, cs=w76; i<5; ++i) (*rr++) += (*cs++);
  /* #99: @75 = (@40+@75) */
  for (i=0, rr=w75, cr=w40, cs=w75; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #100: @58 = horzcat(@66, @67, @69, @71, @73, @75) */
  rr=w58;
  for (i=0, cs=w66; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w69; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w75; i<5; ++i) *rr++ = *cs++;
  /* #101: @48 = horzcat(@42, @43, @44, @45, @46, @47) */
  rr=w48;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  /* #102: @5 = 0x6 */
  /* #103: @56 = horzcat(@50, @51, @52, @53, @54, @55) */
  rr=w56;
  for (i=0, cs=w50; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<66; ++i) *rr++ = *cs++;
  /* #104: @35 = zeros(1x6,0nz) */
  /* #105: {@41, NULL, NULL} = fwd6_ode(@11, @2, @12, @4, @13, @3, @15, @16, @58, @48, @5, @56, @35) */
  arg1[0]=w11;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w58;
  arg1[9]=w48;
  arg1[10]=0;
  arg1[11]=w56;
  arg1[12]=0;
  res1[0]=w41;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #106: {@11, @66, @67, @69, @71, @73} = horzsplit(@41) */
  casadi_copy(w41, 5, w11);
  casadi_copy(w41+5, 5, w66);
  casadi_copy(w41+10, 5, w67);
  casadi_copy(w41+15, 5, w69);
  casadi_copy(w41+20, 5, w71);
  casadi_copy(w41+25, 5, w73);
  /* #107: @75 = (2.*@11) */
  for (i=0, rr=w75, cs=w11; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #108: @75 = (@1+@75) */
  for (i=0, rr=w75, cr=w1, cs=w75; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #109: @12 = zeros(5x1,0nz) */
  /* #110: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #111: @64 = (@10*@32) */
  w64  = (w10*w32);
  /* #112: @76 = (@14*@64) */
  for (i=0, rr=w76, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w64);
  /* #113: @77 = (@18*@11) */
  for (i=0, rr=w77, cs=w11; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #114: @76 = (@76+@77) */
  for (i=0, rr=w76, cs=w77; i<5; ++i) (*rr++) += (*cs++);
  /* #115: @76 = (@0+@76) */
  for (i=0, rr=w76, cr=w0, cs=w76; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #116: @64 = (@10*@65) */
  w64  = (w10*w65);
  /* #117: @77 = (@14*@64) */
  for (i=0, rr=w77, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w64);
  /* #118: @78 = (@18*@66) */
  for (i=0, rr=w78, cs=w66; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #119: @77 = (@77+@78) */
  for (i=0, rr=w77, cs=w78; i<5; ++i) (*rr++) += (*cs++);
  /* #120: @77 = (@36+@77) */
  for (i=0, rr=w77, cr=w36, cs=w77; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #121: @64 = (@10*@68) */
  w64  = (w10*w68);
  /* #122: @78 = (@14*@64) */
  for (i=0, rr=w78, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w64);
  /* #123: @79 = (@18*@67) */
  for (i=0, rr=w79, cs=w67; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #124: @78 = (@78+@79) */
  for (i=0, rr=w78, cs=w79; i<5; ++i) (*rr++) += (*cs++);
  /* #125: @78 = (@37+@78) */
  for (i=0, rr=w78, cr=w37, cs=w78; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #126: @64 = (@10*@70) */
  w64  = (w10*w70);
  /* #127: @79 = (@14*@64) */
  for (i=0, rr=w79, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w64);
  /* #128: @80 = (@18*@69) */
  for (i=0, rr=w80, cs=w69; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #129: @79 = (@79+@80) */
  for (i=0, rr=w79, cs=w80; i<5; ++i) (*rr++) += (*cs++);
  /* #130: @79 = (@38+@79) */
  for (i=0, rr=w79, cr=w38, cs=w79; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #131: @64 = (@10*@72) */
  w64  = (w10*w72);
  /* #132: @80 = (@14*@64) */
  for (i=0, rr=w80, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w64);
  /* #133: @81 = (@18*@71) */
  for (i=0, rr=w81, cs=w71; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #134: @80 = (@80+@81) */
  for (i=0, rr=w80, cs=w81; i<5; ++i) (*rr++) += (*cs++);
  /* #135: @80 = (@39+@80) */
  for (i=0, rr=w80, cr=w39, cs=w80; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #136: @10 = (@10*@74) */
  w10 *= w74;
  /* #137: @81 = (@14*@10) */
  for (i=0, rr=w81, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w10);
  /* #138: @82 = (@18*@73) */
  for (i=0, rr=w82, cs=w73; i<5; ++i) (*rr++)  = (w18*(*cs++));
  /* #139: @81 = (@81+@82) */
  for (i=0, rr=w81, cs=w82; i<5; ++i) (*rr++) += (*cs++);
  /* #140: @81 = (@40+@81) */
  for (i=0, rr=w81, cr=w40, cs=w81; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #141: @41 = horzcat(@76, @77, @78, @79, @80, @81) */
  rr=w41;
  for (i=0, cs=w76; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w77; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w78; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w79; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w80; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w81; i<5; ++i) *rr++ = *cs++;
  /* #142: @48 = horzcat(@42, @43, @44, @45, @46, @47) */
  rr=w48;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  /* #143: @13 = 0x6 */
  /* #144: @56 = horzcat(@50, @51, @52, @53, @54, @55) */
  rr=w56;
  for (i=0, cs=w50; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<66; ++i) *rr++ = *cs++;
  /* #145: @3 = zeros(1x6,0nz) */
  /* #146: {@58, NULL, NULL} = fwd6_ode(@19, @2, @20, @4, @21, @12, @23, @24, @41, @48, @13, @56, @3) */
  arg1[0]=w19;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w41;
  arg1[9]=w48;
  arg1[10]=0;
  arg1[11]=w56;
  arg1[12]=0;
  res1[0]=w58;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #147: {@19, @76, @77, @78, @79, @80} = horzsplit(@58) */
  casadi_copy(w58, 5, w19);
  casadi_copy(w58+5, 5, w76);
  casadi_copy(w58+10, 5, w77);
  casadi_copy(w58+15, 5, w78);
  casadi_copy(w58+20, 5, w79);
  casadi_copy(w58+25, 5, w80);
  /* #148: @81 = (2.*@19) */
  for (i=0, rr=w81, cs=w19; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #149: @75 = (@75+@81) */
  for (i=0, rr=w75, cs=w81; i<5; ++i) (*rr++) += (*cs++);
  /* #150: @20 = zeros(5x1,0nz) */
  /* #151: @81 = (@22*@32) */
  for (i=0, rr=w81, cr=w22; i<5; ++i) (*rr++)  = ((*cr++)*w32);
  /* #152: @82 = (@9*@19) */
  for (i=0, rr=w82, cs=w19; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #153: @81 = (@81+@82) */
  for (i=0, rr=w81, cs=w82; i<5; ++i) (*rr++) += (*cs++);
  /* #154: @81 = (@0+@81) */
  for (i=0, rr=w81, cr=w0, cs=w81; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #155: @82 = (@22*@65) */
  for (i=0, rr=w82, cr=w22; i<5; ++i) (*rr++)  = ((*cr++)*w65);
  /* #156: @83 = (@9*@76) */
  for (i=0, rr=w83, cs=w76; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #157: @82 = (@82+@83) */
  for (i=0, rr=w82, cs=w83; i<5; ++i) (*rr++) += (*cs++);
  /* #158: @82 = (@36+@82) */
  for (i=0, rr=w82, cr=w36, cs=w82; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #159: @83 = (@22*@68) */
  for (i=0, rr=w83, cr=w22; i<5; ++i) (*rr++)  = ((*cr++)*w68);
  /* #160: @84 = (@9*@77) */
  for (i=0, rr=w84, cs=w77; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #161: @83 = (@83+@84) */
  for (i=0, rr=w83, cs=w84; i<5; ++i) (*rr++) += (*cs++);
  /* #162: @83 = (@37+@83) */
  for (i=0, rr=w83, cr=w37, cs=w83; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #163: @84 = (@22*@70) */
  for (i=0, rr=w84, cr=w22; i<5; ++i) (*rr++)  = ((*cr++)*w70);
  /* #164: @85 = (@9*@78) */
  for (i=0, rr=w85, cs=w78; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #165: @84 = (@84+@85) */
  for (i=0, rr=w84, cs=w85; i<5; ++i) (*rr++) += (*cs++);
  /* #166: @84 = (@38+@84) */
  for (i=0, rr=w84, cr=w38, cs=w84; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #167: @85 = (@22*@72) */
  for (i=0, rr=w85, cr=w22; i<5; ++i) (*rr++)  = ((*cr++)*w72);
  /* #168: @86 = (@9*@79) */
  for (i=0, rr=w86, cs=w79; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #169: @85 = (@85+@86) */
  for (i=0, rr=w85, cs=w86; i<5; ++i) (*rr++) += (*cs++);
  /* #170: @85 = (@39+@85) */
  for (i=0, rr=w85, cr=w39, cs=w85; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #171: @86 = (@22*@74) */
  for (i=0, rr=w86, cr=w22; i<5; ++i) (*rr++)  = ((*cr++)*w74);
  /* #172: @87 = (@9*@80) */
  for (i=0, rr=w87, cs=w80; i<5; ++i) (*rr++)  = (w9*(*cs++));
  /* #173: @86 = (@86+@87) */
  for (i=0, rr=w86, cs=w87; i<5; ++i) (*rr++) += (*cs++);
  /* #174: @86 = (@40+@86) */
  for (i=0, rr=w86, cr=w40, cs=w86; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #175: @58 = horzcat(@81, @82, @83, @84, @85, @86) */
  rr=w58;
  for (i=0, cs=w81; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w82; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w84; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w85; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w86; i<5; ++i) *rr++ = *cs++;
  /* #176: @48 = horzcat(@42, @43, @44, @45, @46, @47) */
  rr=w48;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  /* #177: @21 = 0x6 */
  /* #178: @56 = horzcat(@50, @51, @52, @53, @54, @55) */
  rr=w56;
  for (i=0, cs=w50; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<66; ++i) *rr++ = *cs++;
  /* #179: @12 = zeros(1x6,0nz) */
  /* #180: {@41, NULL, NULL} = fwd6_ode(@25, @2, @26, @4, @27, @20, @29, @30, @58, @48, @21, @56, @12) */
  arg1[0]=w25;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w4;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w58;
  arg1[9]=w48;
  arg1[10]=0;
  arg1[11]=w56;
  arg1[12]=0;
  res1[0]=w41;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #181: {@25, @81, @82, @83, @84, @85} = horzsplit(@41) */
  casadi_copy(w41, 5, w25);
  casadi_copy(w41+5, 5, w81);
  casadi_copy(w41+10, 5, w82);
  casadi_copy(w41+15, 5, w83);
  casadi_copy(w41+20, 5, w84);
  casadi_copy(w41+25, 5, w85);
  /* #182: @75 = (@75+@25) */
  for (i=0, rr=w75, cs=w25; i<5; ++i) (*rr++) += (*cs++);
  /* #183: @75 = (@33*@75) */
  for (i=0, rr=w75, cs=w75; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #184: @34 = (@34+@75) */
  for (i=0, rr=w34, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #185: @34 = (@0+@34) */
  for (i=0, rr=w34, cr=w0, cs=w34; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #186: output[0][0] = @34 */
  casadi_copy(w34, 5, res[0]);
  /* #187: @18 = (@31*@65) */
  w18  = (w31*w65);
  /* #188: @34 = (@17*@18) */
  for (i=0, rr=w34, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w18);
  /* #189: @75 = (2.*@66) */
  for (i=0, rr=w75, cs=w66; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #190: @75 = (@59+@75) */
  for (i=0, rr=w75, cr=w59, cs=w75; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #191: @86 = (2.*@76) */
  for (i=0, rr=w86, cs=w76; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #192: @75 = (@75+@86) */
  for (i=0, rr=w75, cs=w86; i<5; ++i) (*rr++) += (*cs++);
  /* #193: @75 = (@75+@81) */
  for (i=0, rr=w75, cs=w81; i<5; ++i) (*rr++) += (*cs++);
  /* #194: @75 = (@33*@75) */
  for (i=0, rr=w75, cs=w75; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #195: @34 = (@34+@75) */
  for (i=0, rr=w34, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #196: @34 = (@36+@34) */
  for (i=0, rr=w34, cr=w36, cs=w34; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #197: output[0][1] = @34 */
  if (res[0]) casadi_copy(w34, 5, res[0]+5);
  /* #198: @18 = (@31*@68) */
  w18  = (w31*w68);
  /* #199: @34 = (@17*@18) */
  for (i=0, rr=w34, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w18);
  /* #200: @75 = (2.*@67) */
  for (i=0, rr=w75, cs=w67; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #201: @75 = (@60+@75) */
  for (i=0, rr=w75, cr=w60, cs=w75; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #202: @86 = (2.*@77) */
  for (i=0, rr=w86, cs=w77; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #203: @75 = (@75+@86) */
  for (i=0, rr=w75, cs=w86; i<5; ++i) (*rr++) += (*cs++);
  /* #204: @75 = (@75+@82) */
  for (i=0, rr=w75, cs=w82; i<5; ++i) (*rr++) += (*cs++);
  /* #205: @75 = (@33*@75) */
  for (i=0, rr=w75, cs=w75; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #206: @34 = (@34+@75) */
  for (i=0, rr=w34, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #207: @34 = (@37+@34) */
  for (i=0, rr=w34, cr=w37, cs=w34; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #208: output[0][2] = @34 */
  if (res[0]) casadi_copy(w34, 5, res[0]+10);
  /* #209: @18 = (@31*@70) */
  w18  = (w31*w70);
  /* #210: @34 = (@17*@18) */
  for (i=0, rr=w34, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w18);
  /* #211: @75 = (2.*@69) */
  for (i=0, rr=w75, cs=w69; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #212: @75 = (@61+@75) */
  for (i=0, rr=w75, cr=w61, cs=w75; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #213: @86 = (2.*@78) */
  for (i=0, rr=w86, cs=w78; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #214: @75 = (@75+@86) */
  for (i=0, rr=w75, cs=w86; i<5; ++i) (*rr++) += (*cs++);
  /* #215: @75 = (@75+@83) */
  for (i=0, rr=w75, cs=w83; i<5; ++i) (*rr++) += (*cs++);
  /* #216: @75 = (@33*@75) */
  for (i=0, rr=w75, cs=w75; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #217: @34 = (@34+@75) */
  for (i=0, rr=w34, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #218: @34 = (@38+@34) */
  for (i=0, rr=w34, cr=w38, cs=w34; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #219: output[0][3] = @34 */
  if (res[0]) casadi_copy(w34, 5, res[0]+15);
  /* #220: @18 = (@31*@72) */
  w18  = (w31*w72);
  /* #221: @34 = (@17*@18) */
  for (i=0, rr=w34, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w18);
  /* #222: @75 = (2.*@71) */
  for (i=0, rr=w75, cs=w71; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #223: @75 = (@62+@75) */
  for (i=0, rr=w75, cr=w62, cs=w75; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #224: @86 = (2.*@79) */
  for (i=0, rr=w86, cs=w79; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #225: @75 = (@75+@86) */
  for (i=0, rr=w75, cs=w86; i<5; ++i) (*rr++) += (*cs++);
  /* #226: @75 = (@75+@84) */
  for (i=0, rr=w75, cs=w84; i<5; ++i) (*rr++) += (*cs++);
  /* #227: @75 = (@33*@75) */
  for (i=0, rr=w75, cs=w75; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #228: @34 = (@34+@75) */
  for (i=0, rr=w34, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #229: @34 = (@39+@34) */
  for (i=0, rr=w34, cr=w39, cs=w34; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #230: output[0][4] = @34 */
  if (res[0]) casadi_copy(w34, 5, res[0]+20);
  /* #231: @31 = (@31*@74) */
  w31 *= w74;
  /* #232: @17 = (@17*@31) */
  for (i=0, rr=w17; i<5; ++i) (*rr++) *= w31;
  /* #233: @34 = (2.*@73) */
  for (i=0, rr=w34, cs=w73; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #234: @34 = (@63+@34) */
  for (i=0, rr=w34, cr=w63, cs=w34; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #235: @75 = (2.*@80) */
  for (i=0, rr=w75, cs=w80; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #236: @34 = (@34+@75) */
  for (i=0, rr=w34, cs=w75; i<5; ++i) (*rr++) += (*cs++);
  /* #237: @34 = (@34+@85) */
  for (i=0, rr=w34, cs=w85; i<5; ++i) (*rr++) += (*cs++);
  /* #238: @34 = (@33*@34) */
  for (i=0, rr=w34, cs=w34; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #239: @17 = (@17+@34) */
  for (i=0, rr=w17, cs=w34; i<5; ++i) (*rr++) += (*cs++);
  /* #240: @17 = (@40+@17) */
  for (i=0, rr=w17, cr=w40, cs=w17; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #241: output[0][5] = @17 */
  if (res[0]) casadi_copy(w17, 5, res[0]+25);
  /* #242: output[1][0] = @0 */
  casadi_copy(w0, 5, res[1]);
  /* #243: output[1][1] = @1 */
  if (res[1]) casadi_copy(w1, 5, res[1]+5);
  /* #244: @33 = 0.5 */
  w33 = 5.0000000000000000e-01;
  /* #245: @31 = 2 */
  w31 = 2.;
  /* #246: @31 = (@31/@9) */
  w31 /= w9;
  /* #247: @0 = (@11-@1) */
  for (i=0, rr=w0, cr=w11, cs=w1; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #248: @0 = (@31*@0) */
  for (i=0, rr=w0, cs=w0; i<5; ++i) (*rr++)  = (w31*(*cs++));
  /* #249: @17 = (@14-@6) */
  for (i=0, rr=w17, cr=w14, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #250: @18 = (@31/@9) */
  w18  = (w31/w9);
  /* #251: @10 = (@18*@32) */
  w10  = (w18*w32);
  /* #252: @34 = (@17*@10) */
  for (i=0, rr=w34, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w10);
  /* #253: @0 = (@0-@34) */
  for (i=0, rr=w0, cs=w34; i<5; ++i) (*rr++) -= (*cs++);
  /* #254: @0 = (@33*@0) */
  for (i=0, rr=w0, cs=w0; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #255: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 5, res[1]+10);
  /* #256: @10 = 0.166667 */
  w10 = 1.6666666666666666e-01;
  /* #257: @64 = 4 */
  w64 = 4.;
  /* #258: @88 = sq(@9) */
  w88 = casadi_sq( w9 );
  /* #259: @64 = (@64/@88) */
  w64 /= w88;
  /* #260: @11 = (@19-@11) */
  for (i=0, rr=w11, cr=w19, cs=w11; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #261: @11 = (@64*@11) */
  for (i=0, rr=w11, cs=w11; i<5; ++i) (*rr++)  = (w64*(*cs++));
  /* #262: @14 = (@22-@14) */
  for (i=0, rr=w14, cr=w22, cs=w14; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #263: @88 = (@64/@88) */
  w88  = (w64/w88);
  /* #264: @89 = (2.*@9) */
  w89 = (2.* w9 );
  /* #265: @90 = (@89*@32) */
  w90  = (w89*w32);
  /* #266: @90 = (@88*@90) */
  w90  = (w88*w90);
  /* #267: @0 = (@14*@90) */
  for (i=0, rr=w0, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w90);
  /* #268: @11 = (@11-@0) */
  for (i=0, rr=w11, cs=w0; i<5; ++i) (*rr++) -= (*cs++);
  /* #269: @11 = (@10*@11) */
  for (i=0, rr=w11, cs=w11; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #270: output[1][3] = @11 */
  if (res[1]) casadi_copy(w11, 5, res[1]+15);
  /* #271: @90 = 0.0416667 */
  w90 = 4.1666666666666664e-02;
  /* #272: @91 = 4 */
  w91 = 4.;
  /* #273: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #274: @25 = (@25-@19) */
  for (i=0, rr=w25, cs=w19; i<5; ++i) (*rr++) -= (*cs++);
  /* #275: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w1; i<5; ++i) (*rr++) += (*cs++);
  /* #276: @25 = (@91*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #277: @92 = 3 */
  w92 = 3.;
  /* #278: @93 = pow(@9,@92) */
  w93  = pow(w9,w92);
  /* #279: @25 = (@25/@93) */
  for (i=0, rr=w25; i<5; ++i) (*rr++) /= w93;
  /* #280: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #281: @28 = (@28-@22) */
  for (i=0, rr=w28, cs=w22; i<5; ++i) (*rr++) -= (*cs++);
  /* #282: @28 = (@28+@6) */
  for (i=0, rr=w28, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #283: @28 = (@91*@28) */
  for (i=0, rr=w28, cs=w28; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #284: @28 = (@28/@93) */
  for (i=0, rr=w28; i<5; ++i) (*rr++) /= w93;
  /* #285: @28 = (@28/@93) */
  for (i=0, rr=w28; i<5; ++i) (*rr++) /= w93;
  /* #286: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #287: @92 = (@92*@9) */
  w92 *= w9;
  /* #288: @32 = (@92*@32) */
  w32  = (w92*w32);
  /* #289: @6 = (@28*@32) */
  for (i=0, rr=w6, cr=w28; i<5; ++i) (*rr++)  = ((*cr++)*w32);
  /* #290: @25 = (@25-@6) */
  for (i=0, rr=w25, cs=w6; i<5; ++i) (*rr++) -= (*cs++);
  /* #291: @25 = (@90*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w90*(*cs++));
  /* #292: output[1][4] = @25 */
  if (res[1]) casadi_copy(w25, 5, res[1]+20);
  /* #293: output[1][5] = @36 */
  if (res[1]) casadi_copy(w36, 5, res[1]+25);
  /* #294: output[1][6] = @59 */
  if (res[1]) casadi_copy(w59, 5, res[1]+30);
  /* #295: @36 = (@66-@59) */
  for (i=0, rr=w36, cr=w66, cs=w59; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #296: @36 = (@31*@36) */
  for (i=0, rr=w36, cs=w36; i<5; ++i) (*rr++)  = (w31*(*cs++));
  /* #297: @32 = (@18*@65) */
  w32  = (w18*w65);
  /* #298: @25 = (@17*@32) */
  for (i=0, rr=w25, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w32);
  /* #299: @36 = (@36-@25) */
  for (i=0, rr=w36, cs=w25; i<5; ++i) (*rr++) -= (*cs++);
  /* #300: @36 = (@33*@36) */
  for (i=0, rr=w36, cs=w36; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #301: output[1][7] = @36 */
  if (res[1]) casadi_copy(w36, 5, res[1]+35);
  /* #302: @66 = (@76-@66) */
  for (i=0, rr=w66, cr=w76, cs=w66; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #303: @66 = (@64*@66) */
  for (i=0, rr=w66, cs=w66; i<5; ++i) (*rr++)  = (w64*(*cs++));
  /* #304: @32 = (@89*@65) */
  w32  = (w89*w65);
  /* #305: @32 = (@88*@32) */
  w32  = (w88*w32);
  /* #306: @36 = (@14*@32) */
  for (i=0, rr=w36, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w32);
  /* #307: @66 = (@66-@36) */
  for (i=0, rr=w66, cs=w36; i<5; ++i) (*rr++) -= (*cs++);
  /* #308: @66 = (@10*@66) */
  for (i=0, rr=w66, cs=w66; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #309: output[1][8] = @66 */
  if (res[1]) casadi_copy(w66, 5, res[1]+40);
  /* #310: @76 = (2.*@76) */
  for (i=0, rr=w76, cs=w76; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #311: @81 = (@81-@76) */
  for (i=0, rr=w81, cs=w76; i<5; ++i) (*rr++) -= (*cs++);
  /* #312: @81 = (@81+@59) */
  for (i=0, rr=w81, cs=w59; i<5; ++i) (*rr++) += (*cs++);
  /* #313: @81 = (@91*@81) */
  for (i=0, rr=w81, cs=w81; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #314: @81 = (@81/@93) */
  for (i=0, rr=w81; i<5; ++i) (*rr++) /= w93;
  /* #315: @65 = (@92*@65) */
  w65  = (w92*w65);
  /* #316: @59 = (@28*@65) */
  for (i=0, rr=w59, cr=w28; i<5; ++i) (*rr++)  = ((*cr++)*w65);
  /* #317: @81 = (@81-@59) */
  for (i=0, rr=w81, cs=w59; i<5; ++i) (*rr++) -= (*cs++);
  /* #318: @81 = (@90*@81) */
  for (i=0, rr=w81, cs=w81; i<5; ++i) (*rr++)  = (w90*(*cs++));
  /* #319: output[1][9] = @81 */
  if (res[1]) casadi_copy(w81, 5, res[1]+45);
  /* #320: output[1][10] = @37 */
  if (res[1]) casadi_copy(w37, 5, res[1]+50);
  /* #321: output[1][11] = @60 */
  if (res[1]) casadi_copy(w60, 5, res[1]+55);
  /* #322: @37 = (@67-@60) */
  for (i=0, rr=w37, cr=w67, cs=w60; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #323: @37 = (@31*@37) */
  for (i=0, rr=w37, cs=w37; i<5; ++i) (*rr++)  = (w31*(*cs++));
  /* #324: @65 = (@18*@68) */
  w65  = (w18*w68);
  /* #325: @81 = (@17*@65) */
  for (i=0, rr=w81, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w65);
  /* #326: @37 = (@37-@81) */
  for (i=0, rr=w37, cs=w81; i<5; ++i) (*rr++) -= (*cs++);
  /* #327: @37 = (@33*@37) */
  for (i=0, rr=w37, cs=w37; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #328: output[1][12] = @37 */
  if (res[1]) casadi_copy(w37, 5, res[1]+60);
  /* #329: @67 = (@77-@67) */
  for (i=0, rr=w67, cr=w77, cs=w67; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #330: @67 = (@64*@67) */
  for (i=0, rr=w67, cs=w67; i<5; ++i) (*rr++)  = (w64*(*cs++));
  /* #331: @65 = (@89*@68) */
  w65  = (w89*w68);
  /* #332: @65 = (@88*@65) */
  w65  = (w88*w65);
  /* #333: @37 = (@14*@65) */
  for (i=0, rr=w37, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w65);
  /* #334: @67 = (@67-@37) */
  for (i=0, rr=w67, cs=w37; i<5; ++i) (*rr++) -= (*cs++);
  /* #335: @67 = (@10*@67) */
  for (i=0, rr=w67, cs=w67; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #336: output[1][13] = @67 */
  if (res[1]) casadi_copy(w67, 5, res[1]+65);
  /* #337: @77 = (2.*@77) */
  for (i=0, rr=w77, cs=w77; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #338: @82 = (@82-@77) */
  for (i=0, rr=w82, cs=w77; i<5; ++i) (*rr++) -= (*cs++);
  /* #339: @82 = (@82+@60) */
  for (i=0, rr=w82, cs=w60; i<5; ++i) (*rr++) += (*cs++);
  /* #340: @82 = (@91*@82) */
  for (i=0, rr=w82, cs=w82; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #341: @82 = (@82/@93) */
  for (i=0, rr=w82; i<5; ++i) (*rr++) /= w93;
  /* #342: @68 = (@92*@68) */
  w68  = (w92*w68);
  /* #343: @60 = (@28*@68) */
  for (i=0, rr=w60, cr=w28; i<5; ++i) (*rr++)  = ((*cr++)*w68);
  /* #344: @82 = (@82-@60) */
  for (i=0, rr=w82, cs=w60; i<5; ++i) (*rr++) -= (*cs++);
  /* #345: @82 = (@90*@82) */
  for (i=0, rr=w82, cs=w82; i<5; ++i) (*rr++)  = (w90*(*cs++));
  /* #346: output[1][14] = @82 */
  if (res[1]) casadi_copy(w82, 5, res[1]+70);
  /* #347: output[1][15] = @38 */
  if (res[1]) casadi_copy(w38, 5, res[1]+75);
  /* #348: output[1][16] = @61 */
  if (res[1]) casadi_copy(w61, 5, res[1]+80);
  /* #349: @38 = (@69-@61) */
  for (i=0, rr=w38, cr=w69, cs=w61; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #350: @38 = (@31*@38) */
  for (i=0, rr=w38, cs=w38; i<5; ++i) (*rr++)  = (w31*(*cs++));
  /* #351: @68 = (@18*@70) */
  w68  = (w18*w70);
  /* #352: @82 = (@17*@68) */
  for (i=0, rr=w82, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w68);
  /* #353: @38 = (@38-@82) */
  for (i=0, rr=w38, cs=w82; i<5; ++i) (*rr++) -= (*cs++);
  /* #354: @38 = (@33*@38) */
  for (i=0, rr=w38, cs=w38; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #355: output[1][17] = @38 */
  if (res[1]) casadi_copy(w38, 5, res[1]+85);
  /* #356: @69 = (@78-@69) */
  for (i=0, rr=w69, cr=w78, cs=w69; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #357: @69 = (@64*@69) */
  for (i=0, rr=w69, cs=w69; i<5; ++i) (*rr++)  = (w64*(*cs++));
  /* #358: @68 = (@89*@70) */
  w68  = (w89*w70);
  /* #359: @68 = (@88*@68) */
  w68  = (w88*w68);
  /* #360: @38 = (@14*@68) */
  for (i=0, rr=w38, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w68);
  /* #361: @69 = (@69-@38) */
  for (i=0, rr=w69, cs=w38; i<5; ++i) (*rr++) -= (*cs++);
  /* #362: @69 = (@10*@69) */
  for (i=0, rr=w69, cs=w69; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #363: output[1][18] = @69 */
  if (res[1]) casadi_copy(w69, 5, res[1]+90);
  /* #364: @78 = (2.*@78) */
  for (i=0, rr=w78, cs=w78; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #365: @83 = (@83-@78) */
  for (i=0, rr=w83, cs=w78; i<5; ++i) (*rr++) -= (*cs++);
  /* #366: @83 = (@83+@61) */
  for (i=0, rr=w83, cs=w61; i<5; ++i) (*rr++) += (*cs++);
  /* #367: @83 = (@91*@83) */
  for (i=0, rr=w83, cs=w83; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #368: @83 = (@83/@93) */
  for (i=0, rr=w83; i<5; ++i) (*rr++) /= w93;
  /* #369: @70 = (@92*@70) */
  w70  = (w92*w70);
  /* #370: @61 = (@28*@70) */
  for (i=0, rr=w61, cr=w28; i<5; ++i) (*rr++)  = ((*cr++)*w70);
  /* #371: @83 = (@83-@61) */
  for (i=0, rr=w83, cs=w61; i<5; ++i) (*rr++) -= (*cs++);
  /* #372: @83 = (@90*@83) */
  for (i=0, rr=w83, cs=w83; i<5; ++i) (*rr++)  = (w90*(*cs++));
  /* #373: output[1][19] = @83 */
  if (res[1]) casadi_copy(w83, 5, res[1]+95);
  /* #374: output[1][20] = @39 */
  if (res[1]) casadi_copy(w39, 5, res[1]+100);
  /* #375: output[1][21] = @62 */
  if (res[1]) casadi_copy(w62, 5, res[1]+105);
  /* #376: @39 = (@71-@62) */
  for (i=0, rr=w39, cr=w71, cs=w62; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #377: @39 = (@31*@39) */
  for (i=0, rr=w39, cs=w39; i<5; ++i) (*rr++)  = (w31*(*cs++));
  /* #378: @70 = (@18*@72) */
  w70  = (w18*w72);
  /* #379: @83 = (@17*@70) */
  for (i=0, rr=w83, cr=w17; i<5; ++i) (*rr++)  = ((*cr++)*w70);
  /* #380: @39 = (@39-@83) */
  for (i=0, rr=w39, cs=w83; i<5; ++i) (*rr++) -= (*cs++);
  /* #381: @39 = (@33*@39) */
  for (i=0, rr=w39, cs=w39; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #382: output[1][22] = @39 */
  if (res[1]) casadi_copy(w39, 5, res[1]+110);
  /* #383: @71 = (@79-@71) */
  for (i=0, rr=w71, cr=w79, cs=w71; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #384: @71 = (@64*@71) */
  for (i=0, rr=w71, cs=w71; i<5; ++i) (*rr++)  = (w64*(*cs++));
  /* #385: @70 = (@89*@72) */
  w70  = (w89*w72);
  /* #386: @70 = (@88*@70) */
  w70  = (w88*w70);
  /* #387: @39 = (@14*@70) */
  for (i=0, rr=w39, cr=w14; i<5; ++i) (*rr++)  = ((*cr++)*w70);
  /* #388: @71 = (@71-@39) */
  for (i=0, rr=w71, cs=w39; i<5; ++i) (*rr++) -= (*cs++);
  /* #389: @71 = (@10*@71) */
  for (i=0, rr=w71, cs=w71; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #390: output[1][23] = @71 */
  if (res[1]) casadi_copy(w71, 5, res[1]+115);
  /* #391: @79 = (2.*@79) */
  for (i=0, rr=w79, cs=w79; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #392: @84 = (@84-@79) */
  for (i=0, rr=w84, cs=w79; i<5; ++i) (*rr++) -= (*cs++);
  /* #393: @84 = (@84+@62) */
  for (i=0, rr=w84, cs=w62; i<5; ++i) (*rr++) += (*cs++);
  /* #394: @84 = (@91*@84) */
  for (i=0, rr=w84, cs=w84; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #395: @84 = (@84/@93) */
  for (i=0, rr=w84; i<5; ++i) (*rr++) /= w93;
  /* #396: @72 = (@92*@72) */
  w72  = (w92*w72);
  /* #397: @62 = (@28*@72) */
  for (i=0, rr=w62, cr=w28; i<5; ++i) (*rr++)  = ((*cr++)*w72);
  /* #398: @84 = (@84-@62) */
  for (i=0, rr=w84, cs=w62; i<5; ++i) (*rr++) -= (*cs++);
  /* #399: @84 = (@90*@84) */
  for (i=0, rr=w84, cs=w84; i<5; ++i) (*rr++)  = (w90*(*cs++));
  /* #400: output[1][24] = @84 */
  if (res[1]) casadi_copy(w84, 5, res[1]+120);
  /* #401: output[1][25] = @40 */
  if (res[1]) casadi_copy(w40, 5, res[1]+125);
  /* #402: output[1][26] = @63 */
  if (res[1]) casadi_copy(w63, 5, res[1]+130);
  /* #403: @40 = (@73-@63) */
  for (i=0, rr=w40, cr=w73, cs=w63; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #404: @40 = (@31*@40) */
  for (i=0, rr=w40, cs=w40; i<5; ++i) (*rr++)  = (w31*(*cs++));
  /* #405: @18 = (@18*@74) */
  w18 *= w74;
  /* #406: @17 = (@17*@18) */
  for (i=0, rr=w17; i<5; ++i) (*rr++) *= w18;
  /* #407: @40 = (@40-@17) */
  for (i=0, rr=w40, cs=w17; i<5; ++i) (*rr++) -= (*cs++);
  /* #408: @40 = (@33*@40) */
  for (i=0, rr=w40, cs=w40; i<5; ++i) (*rr++)  = (w33*(*cs++));
  /* #409: output[1][27] = @40 */
  if (res[1]) casadi_copy(w40, 5, res[1]+135);
  /* #410: @73 = (@80-@73) */
  for (i=0, rr=w73, cr=w80, cs=w73; i<5; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #411: @73 = (@64*@73) */
  for (i=0, rr=w73, cs=w73; i<5; ++i) (*rr++)  = (w64*(*cs++));
  /* #412: @89 = (@89*@74) */
  w89 *= w74;
  /* #413: @88 = (@88*@89) */
  w88 *= w89;
  /* #414: @14 = (@14*@88) */
  for (i=0, rr=w14; i<5; ++i) (*rr++) *= w88;
  /* #415: @73 = (@73-@14) */
  for (i=0, rr=w73, cs=w14; i<5; ++i) (*rr++) -= (*cs++);
  /* #416: @73 = (@10*@73) */
  for (i=0, rr=w73, cs=w73; i<5; ++i) (*rr++)  = (w10*(*cs++));
  /* #417: output[1][28] = @73 */
  if (res[1]) casadi_copy(w73, 5, res[1]+140);
  /* #418: @80 = (2.*@80) */
  for (i=0, rr=w80, cs=w80; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #419: @85 = (@85-@80) */
  for (i=0, rr=w85, cs=w80; i<5; ++i) (*rr++) -= (*cs++);
  /* #420: @85 = (@85+@63) */
  for (i=0, rr=w85, cs=w63; i<5; ++i) (*rr++) += (*cs++);
  /* #421: @85 = (@91*@85) */
  for (i=0, rr=w85, cs=w85; i<5; ++i) (*rr++)  = (w91*(*cs++));
  /* #422: @85 = (@85/@93) */
  for (i=0, rr=w85; i<5; ++i) (*rr++) /= w93;
  /* #423: @92 = (@92*@74) */
  w92 *= w74;
  /* #424: @28 = (@28*@92) */
  for (i=0, rr=w28; i<5; ++i) (*rr++) *= w92;
  /* #425: @85 = (@85-@28) */
  for (i=0, rr=w85, cs=w28; i<5; ++i) (*rr++) -= (*cs++);
  /* #426: @85 = (@90*@85) */
  for (i=0, rr=w85, cs=w85; i<5; ++i) (*rr++)  = (w90*(*cs++));
  /* #427: output[1][29] = @85 */
  if (res[1]) casadi_copy(w85, 5, res[1]+145);
  return 0;
}

/* fwd6_F:(x0[5],u[3],T,t0,p[66],out_xf[5x1,0nz],out_Xi[5x2,0nz],out_poly_coeff[5x5,0nz],out_qf[0],out_zf[0],out_Zi[0],out_poly_coeff_z[],fwd_x0[5x6],fwd_u[3x6],fwd_T[1x6],fwd_t0[1x6],fwd_p[66x6])->(fwd_xf[5x6],fwd_Xi[5x12],fwd_poly_coeff[5x30],fwd_qf[0x6],fwd_zf[0x6],fwd_Zi[0x6],fwd_poly_coeff_z[]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+7, *rr;
  const casadi_real **arg1=arg+17, *cs;
  casadi_real *w0=w+1259, *w1=w+1264, w2, w3, *w4=w+1269, *w10=w+1335, *w11=w+1340, *w12=w+1345, *w13=w+1350, *w14=w+1355, *w15=w+1360, *w16=w+1365, *w17=w+1395, *w18=w+1398, *w19=w+1401, *w20=w+1404, *w21=w+1407, *w22=w+1410, *w23=w+1413, w24, w25, w26, w27, w28, w29, *w30=w+1437, *w31=w+1443, *w32=w+1449, *w33=w+1515, *w34=w+1581, *w35=w+1647, *w36=w+1713, *w37=w+1779, *w38=w+1845, *w39=w+2241, *w40=w+2271, *w41=w+2421, *w42=w+2426, *w43=w+2431, *w44=w+2436;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w1);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #4: @4 = input[4][0] */
  casadi_copy(arg[4], 66, w4);
  /* #5: @5 = zeros(5x1,0nz) */
  /* #6: @6 = zeros(5x5,0nz) */
  /* #7: {NULL, NULL, @7, @8, @9} = F(@0, @1, @2, @3, @4) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=(&w2);
  arg1[3]=(&w3);
  arg1[4]=w4;
  res1[0]=0;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @10 = input[12][0] */
  casadi_copy(arg[12], 5, w10);
  /* #9: @11 = input[12][1] */
  casadi_copy(arg[12] ? arg[12]+5 : 0, 5, w11);
  /* #10: @12 = input[12][2] */
  casadi_copy(arg[12] ? arg[12]+10 : 0, 5, w12);
  /* #11: @13 = input[12][3] */
  casadi_copy(arg[12] ? arg[12]+15 : 0, 5, w13);
  /* #12: @14 = input[12][4] */
  casadi_copy(arg[12] ? arg[12]+20 : 0, 5, w14);
  /* #13: @15 = input[12][5] */
  casadi_copy(arg[12] ? arg[12]+25 : 0, 5, w15);
  /* #14: @16 = horzcat(@10, @11, @12, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<5; ++i) *rr++ = *cs++;
  /* #15: @17 = input[13][0] */
  casadi_copy(arg[13], 3, w17);
  /* #16: @18 = input[13][1] */
  casadi_copy(arg[13] ? arg[13]+3 : 0, 3, w18);
  /* #17: @19 = input[13][2] */
  casadi_copy(arg[13] ? arg[13]+6 : 0, 3, w19);
  /* #18: @20 = input[13][3] */
  casadi_copy(arg[13] ? arg[13]+9 : 0, 3, w20);
  /* #19: @21 = input[13][4] */
  casadi_copy(arg[13] ? arg[13]+12 : 0, 3, w21);
  /* #20: @22 = input[13][5] */
  casadi_copy(arg[13] ? arg[13]+15 : 0, 3, w22);
  /* #21: @23 = horzcat(@17, @18, @19, @20, @21, @22) */
  rr=w23;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #22: @24 = input[15][0] */
  w24 = arg[15] ? arg[15][0] : 0;
  /* #23: @25 = input[15][1] */
  w25 = arg[15] ? arg[15][1] : 0;
  /* #24: @26 = input[15][2] */
  w26 = arg[15] ? arg[15][2] : 0;
  /* #25: @27 = input[15][3] */
  w27 = arg[15] ? arg[15][3] : 0;
  /* #26: @28 = input[15][4] */
  w28 = arg[15] ? arg[15][4] : 0;
  /* #27: @29 = input[15][5] */
  w29 = arg[15] ? arg[15][5] : 0;
  /* #28: @30 = horzcat(@24, @25, @26, @27, @28, @29) */
  rr=w30;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  /* #29: @24 = input[14][0] */
  w24 = arg[14] ? arg[14][0] : 0;
  /* #30: @25 = input[14][1] */
  w25 = arg[14] ? arg[14][1] : 0;
  /* #31: @26 = input[14][2] */
  w26 = arg[14] ? arg[14][2] : 0;
  /* #32: @27 = input[14][3] */
  w27 = arg[14] ? arg[14][3] : 0;
  /* #33: @28 = input[14][4] */
  w28 = arg[14] ? arg[14][4] : 0;
  /* #34: @29 = input[14][5] */
  w29 = arg[14] ? arg[14][5] : 0;
  /* #35: @31 = horzcat(@24, @25, @26, @27, @28, @29) */
  rr=w31;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  /* #36: @32 = input[16][0] */
  casadi_copy(arg[16], 66, w32);
  /* #37: @33 = input[16][1] */
  casadi_copy(arg[16] ? arg[16]+66 : 0, 66, w33);
  /* #38: @34 = input[16][2] */
  casadi_copy(arg[16] ? arg[16]+132 : 0, 66, w34);
  /* #39: @35 = input[16][3] */
  casadi_copy(arg[16] ? arg[16]+198 : 0, 66, w35);
  /* #40: @36 = input[16][4] */
  casadi_copy(arg[16] ? arg[16]+264 : 0, 66, w36);
  /* #41: @37 = input[16][5] */
  casadi_copy(arg[16] ? arg[16]+330 : 0, 66, w37);
  /* #42: @38 = horzcat(@32, @33, @34, @35, @36, @37) */
  rr=w38;
  for (i=0, cs=w32; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<66; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<66; ++i) *rr++ = *cs++;
  /* #43: {@39, @40, NULL, NULL, NULL} = fwd6_F(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @16, @23, @30, @31, @38) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=(&w2);
  arg1[3]=(&w3);
  arg1[4]=w4;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=w16;
  arg1[11]=w23;
  arg1[12]=w30;
  arg1[13]=w31;
  arg1[14]=w38;
  res1[0]=w39;
  res1[1]=w40;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #44: output[0][0] = @39 */
  casadi_copy(w39, 30, res[0]);
  /* #45: output[1][0] = @10 */
  casadi_copy(w10, 5, res[1]);
  /* #46: {@10, @0, @41, @42, @43, @44} = horzsplit(@39) */
  casadi_copy(w39, 5, w10);
  casadi_copy(w39+5, 5, w0);
  casadi_copy(w39+10, 5, w41);
  casadi_copy(w39+15, 5, w42);
  casadi_copy(w39+20, 5, w43);
  casadi_copy(w39+25, 5, w44);
  /* #47: output[1][1] = @10 */
  if (res[1]) casadi_copy(w10, 5, res[1]+5);
  /* #48: output[1][2] = @11 */
  if (res[1]) casadi_copy(w11, 5, res[1]+10);
  /* #49: output[1][3] = @0 */
  if (res[1]) casadi_copy(w0, 5, res[1]+15);
  /* #50: output[1][4] = @12 */
  if (res[1]) casadi_copy(w12, 5, res[1]+20);
  /* #51: output[1][5] = @41 */
  if (res[1]) casadi_copy(w41, 5, res[1]+25);
  /* #52: output[1][6] = @13 */
  if (res[1]) casadi_copy(w13, 5, res[1]+30);
  /* #53: output[1][7] = @42 */
  if (res[1]) casadi_copy(w42, 5, res[1]+35);
  /* #54: output[1][8] = @14 */
  if (res[1]) casadi_copy(w14, 5, res[1]+40);
  /* #55: output[1][9] = @43 */
  if (res[1]) casadi_copy(w43, 5, res[1]+45);
  /* #56: output[1][10] = @15 */
  if (res[1]) casadi_copy(w15, 5, res[1]+50);
  /* #57: output[1][11] = @44 */
  if (res[1]) casadi_copy(w44, 5, res[1]+55);
  /* #58: output[2][0] = @40 */
  casadi_copy(w40, 150, res[2]);
  return 0;
}

/* rockit_model_dyn_disc_phi_fun_jac:(i0[5],i1[3],i2[66])->(o0[5],o1[8x5,18nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+2446, *w6=w+2451, *w7=w+2454, *w8=w+2458, *w9=w+2478, *w10=w+2498, *w11=w+2518, *w12=w+2584, *w17=w+2589, *w25=w+2607, w27, w28, w29, w30, *w31=w+2613, *w32=w+2643, *w33=w+2646, *w34=w+2664, *w35=w+2670, *w36=w+2676, *w37=w+3072, *w38=w+3102, *w39=w+3107, *w40=w+3112, *w41=w+3117;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = vertcat(@0, @1, @2, @3, @4) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #6: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #7: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #8: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #9: @6 = vertcat(@0, @1, @2) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  /* #10: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #11: @1 = 0 */
  w1 = 0.;
  /* #12: @7 = input[2][0] */
  casadi_copy(arg[2], 4, w7);
  /* #13: @2 = input[2][1] */
  w2 = arg[2] ? arg[2][4] : 0;
  /* #14: @3 = input[2][2] */
  w3 = arg[2] ? arg[2][5] : 0;
  /* #15: @8 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 20, w8);
  /* #16: @9 = input[2][4] */
  casadi_copy(arg[2] ? arg[2]+26 : 0, 20, w9);
  /* #17: @10 = input[2][5] */
  casadi_copy(arg[2] ? arg[2]+46 : 0, 20, w10);
  /* #18: @11 = vertcat(@7, @2, @3, @8, @9, @10) */
  rr=w11;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  *rr++ = w2;
  *rr++ = w3;
  for (i=0, cs=w8; i<20; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<20; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<20; ++i) *rr++ = *cs++;
  /* #19: {@12, NULL, NULL, @13, @14, @15, @16} = F(@5, @6, @0, @1, @11) */
  arg1[0]=w5;
  arg1[1]=w6;
  arg1[2]=(&w0);
  arg1[3]=(&w1);
  arg1[4]=w11;
  res1[0]=w12;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][0] = @12 */
  casadi_copy(w12, 5, res[0]);
  /* #21: @17 = zeros(8x5,18nz) */
  casadi_clear(w17, 18);
  /* #22: @18 = zeros(5x1,0nz) */
  /* #23: @19 = zeros(5x2,0nz) */
  /* #24: @20 = zeros(5x5,0nz) */
  /* #25: @21 = zeros(5x1,0nz) */
  /* #26: @22 = 00 */
  /* #27: @23 = 00 */
  /* #28: @24 = 00 */
  /* #29: @25 = ones(8x1,2nz) */
  casadi_fill(w25, 2, 1.);
  /* #30: {NULL, @2, NULL, NULL, NULL, NULL, @3, NULL} = vertsplit(@25) */
  w2 = w25[0];
  w3 = w25[1];
  /* #31: @26 = 00 */
  /* #32: @4 = vertcat(@22, @23, @24, @3, @26) */
  rr=(&w4);
  *rr++ = w3;
  /* #33: @3 = ones(8x1,1nz) */
  w3 = 1.;
  /* #34: {NULL, NULL, NULL, @27, NULL, NULL, NULL, NULL} = vertsplit(@3) */
  w27 = w3;
  /* #35: @22 = 00 */
  /* #36: @23 = 00 */
  /* #37: @24 = 00 */
  /* #38: @26 = 00 */
  /* #39: @3 = vertcat(@27, @22, @23, @24, @26) */
  rr=(&w3);
  *rr++ = w27;
  /* #40: @22 = 00 */
  /* #41: @27 = ones(8x1,1nz) */
  w27 = 1.;
  /* #42: {NULL, NULL, NULL, NULL, @28, NULL, NULL, NULL} = vertsplit(@27) */
  w28 = w27;
  /* #43: @23 = 00 */
  /* #44: @24 = 00 */
  /* #45: @26 = 00 */
  /* #46: @27 = vertcat(@22, @28, @23, @24, @26) */
  rr=(&w27);
  *rr++ = w28;
  /* #47: @22 = 00 */
  /* #48: @23 = 00 */
  /* #49: @28 = ones(8x1,1nz) */
  w28 = 1.;
  /* #50: {NULL, NULL, NULL, NULL, NULL, @29, NULL, NULL} = vertsplit(@28) */
  w29 = w28;
  /* #51: @24 = 00 */
  /* #52: @26 = 00 */
  /* #53: @28 = vertcat(@22, @23, @29, @24, @26) */
  rr=(&w28);
  *rr++ = w29;
  /* #54: @22 = 00 */
  /* #55: @23 = 00 */
  /* #56: @24 = 00 */
  /* #57: @26 = 00 */
  /* #58: @29 = ones(8x1,1nz) */
  w29 = 1.;
  /* #59: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @30} = vertsplit(@29) */
  w30 = w29;
  /* #60: @29 = vertcat(@22, @23, @24, @26, @30) */
  rr=(&w29);
  *rr++ = w30;
  /* #61: @12 = horzcat(@21, @4, @3, @27, @28, @29) */
  rr=w12;
  *rr++ = w4;
  *rr++ = w3;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  /* #62: @31 = dense(@12) */
  casadi_densify(w12, casadi_s0, w31, 0);
  /* #63: @25 = ones(8x1,2nz) */
  casadi_fill(w25, 2, 1.);
  /* #64: {@4, NULL, @3, NULL, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w4 = w25[0];
  w3 = w25[1];
  /* #65: @21 = 00 */
  /* #66: @25 = vertcat(@4, @21, @3) */
  rr=w25;
  *rr++ = w4;
  *rr++ = w3;
  /* #67: @21 = 00 */
  /* #68: @22 = 00 */
  /* #69: @4 = vertcat(@21, @2, @22) */
  rr=(&w4);
  *rr++ = w2;
  /* #70: @21 = zeros(3x1,0nz) */
  /* #71: @22 = zeros(3x1,0nz) */
  /* #72: @23 = zeros(3x1,0nz) */
  /* #73: @24 = zeros(3x1,0nz) */
  /* #74: @32 = horzcat(@25, @4, @21, @22, @23, @24) */
  rr=w32;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  *rr++ = w4;
  /* #75: @33 = dense(@32) */
  casadi_densify(w32, casadi_s1, w33, 0);
  /* #76: @34 = zeros(1x6) */
  casadi_clear(w34, 6);
  /* #77: @35 = zeros(1x6) */
  casadi_clear(w35, 6);
  /* #78: @36 = zeros(66x6) */
  casadi_clear(w36, 396);
  /* #79: {@37, NULL, NULL, NULL, NULL, NULL, NULL} = fwd6_F(@5, @6, @0, @1, @11, @18, @19, @20, @13, @14, @15, @16, @31, @33, @34, @35, @36) */
  arg1[0]=w5;
  arg1[1]=w6;
  arg1[2]=(&w0);
  arg1[3]=(&w1);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=w31;
  arg1[13]=w33;
  arg1[14]=w34;
  arg1[15]=w35;
  arg1[16]=w36;
  res1[0]=w37;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=0;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #80: {@5, @12, @38, @39, @40, @41} = horzsplit(@37) */
  casadi_copy(w37, 5, w5);
  casadi_copy(w37+5, 5, w12);
  casadi_copy(w37+10, 5, w38);
  casadi_copy(w37+15, 5, w39);
  casadi_copy(w37+20, 5, w40);
  casadi_copy(w37+25, 5, w41);
  /* #81: @7 = @5[:6:3;:2] */
  for (rr=w7, ss=w5+0; ss!=w5+6; ss+=3) for (tt=ss+0; tt!=ss+2; tt+=1) *rr++ = *tt;
  /* #82: (@17[0, 4, 10, 12] = @7) */
  for (cii=casadi_s2, rr=w17, ss=w7; cii!=casadi_s2+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #83: (@17[1, 5, 8, 11, 13] = @12) */
  for (cii=casadi_s3, rr=w17, ss=w12; cii!=casadi_s3+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #84: @25 = @38[:8:4] */
  for (rr=w25, ss=w38+0; ss!=w38+8; ss+=4) *rr++ = *ss;
  /* #85: (@17[2:26:12] = @25) */
  for (rr=w17+2, ss=w25; rr!=w17+26; rr+=12) *rr = *ss++;
  /* #86: @25 = @39[1:7:3] */
  for (rr=w25, ss=w39+1; ss!=w39+7; ss+=3) *rr++ = *ss;
  /* #87: (@17[6:24:9] = @25) */
  for (rr=w17+6, ss=w25; rr!=w17+24; rr+=9) *rr = *ss++;
  /* #88: @7 = @40[0, 1, 2, 4] */
  for (cii=casadi_s4, rr=w7, ss=w40; cii!=casadi_s4+4; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #89: (@17[3, 7, 9, 16] = @7) */
  for (cii=casadi_s5, rr=w17, ss=w7; cii!=casadi_s5+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #90: @0 = @41[4] */
  for (rr=(&w0), ss=w41+4; ss!=w41+5; ss+=1) *rr++ = *ss;
  /* #91: (@17[17] = @0) */
  for (rr=w17+17, ss=(&w0); rr!=w17+18; rr+=1) *rr = *ss++;
  /* #92: output[1][0] = @17 */
  casadi_copy(w17, 18, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_dyn_disc_phi_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_dyn_disc_phi_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_dyn_disc_phi_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 50;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 3122;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
